### ISSUE TITLE
Feature Request: Support copying folders

### ISSUE THREAD

**Issue by ursa34** [RealRaven2000/QuickFolders#103]
There is a 'move folder' function and I think it would be useful to have a "copy" option on that function.

**Comment by RealRaven2000** [comment]
To clarify - move folder is not an explicit command or menu option from QuickFolders but it is implicitely  supported via the following actions:

* hold down Shift and drag+drop one (or multiple) folders on a QuickFolders Tab (representing a folder) - also supports moving folders to any child folders from the dropdown menu of said Tab.
* drag+drop folders onto the quickMove button (or pressing Shift+M while the folder tree is highlighted)

The quickMove button also accepts emails (and the modifier key Ctrl can be held to force copying the emails) so a good way to extend into folders would be using Ctrl during the drop of folders, too.

**Comment by RealRaven2000** [comment]
Here is a test version - you can add folders for copying by dragging them to the quickMove button while holding "Ctrl" key pressed. They will also now be listed in the menu (and you can add more items before executing the folder copy). The icon will differ depending on whether you copy or move:#
![image](https://user-images.githubusercontent.com/6314674/111032826-11e7b480-8406-11eb-937d-294287ad8ba8.png)

[QuickFolders-wx-5.4pre112.zip](https://github.com/RealRaven2000/QuickFolders/files/6134919/QuickFolders-wx-5.4pre112.zip)
(Install this by downloading the zip file and drag into Thunderbird Add-ons manager)

Since it can be a rather big / expensive operation you will get a messagebox asking for confirmation. If you cancel out of this messagebox all search items are cleared again.

**Comment by RealRaven2000** [comment]
Today I added a fix to make it work in Thunderbird 87, too. Looking at the new copy service (`MailServices.copy`) and its usage in Thunderbird, one thing they seem to never do is move folders across servers - the fourth argument "isCopy" is simply set to:
`folders[0].server == targetFolder.server`

Not sure if this is to indicate anything but maybe there is problem _moving_ folders from one account to another - I haven't sufficiently tested this yet. You can see the behavior when you drag around folders within the tree - they are moved within the account but always copied when dropping on another account:

https://searchfox.org/comm-central/source/mail/base/content/folderPane.js#980

**Comment by RealRaven2000** [comment]
Implemented in 5.4 - Released 18/03/2021
