### ISSUE TITLE
The button font size setting seems to affect only the first row of icons

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [RealRaven2000/QuickFolders#104]
![image](https://user-images.githubusercontent.com/47056543/106287485-c060dd00-623e-11eb-8989-818a7ff43b44.png)

![image](https://user-images.githubusercontent.com/47056543/106287599-dec6d880-623e-11eb-849a-15562b8d0b84.png)

QuickFolders 5.2
Windows 10 2009
Thunderbird 78.7.0

**Comment by RealRaven2000** [comment]
Sorry, but I can't see the difference - you mean **the first row of QuickFolders tabs**? Inbox appears "larger" because, Folders containing unread mails are shown in bold font, is that what you are referring to?

Try a really large font size and you will see they are all the same. There is no special rule for the first row. Example with 21px font: 
![image](https://user-images.githubusercontent.com/6314674/106291164-3404e900-6243-11eb-858d-4e56dd4007c6.png)

If you refer to the popup menus underneath the tabs that open up if you want to access sub-folders they use the font size that is configured for your menus via System or your Thunderbird Theme.

**Comment by LinuxOnTheDesktop** [comment]
Ah - my mistake, it seems. Thank you. However: try as I might, I fail to find the option - I think that somewhere there *is* an option - to disable the embolding (but not yellow highlighting) of directories that contain new mail.

**Comment by RealRaven2000** [comment]
> Ah - my mistake, it seems. Thank you. However: try as I might, I fail to find the option - I think that somewhere there _is_ an option - to disable the embolding (but not yellow highlighting) of directories that contain new mail.

It's on the general tab:
![image](https://user-images.githubusercontent.com/6314674/106302432-e2635b00-6250-11eb-9793-4945e0e35a85.png)

the yellow diamond is only highlighting new mail if you got it in the current session. (not on all folders containing unread mail)
