### ISSUE TITLE
Tab-specific Properties overwrites "To Address" when writing from AB

### ISSUE THREAD

**Issue by macdeport** [RealRaven2000/QuickFolders#110]
QuickFolders 5.3pre25: In a given folder if "Tab-specific Properties" is set, this setting totally overwrite Address book "Write" action :-(

**Comment by RealRaven2000** [comment]
What is "Address book _Write_ action". Please describe how you set that up and what you expect Thunderbird to do.

**Comment by macdeport** [comment]
> What is "Address book Write action"

The "Write" button in "Address Book" window:
![thunderbird-address-book-multiselection](https://user-images.githubusercontent.com/26068595/107875064-1465f580-6ebe-11eb-9ff6-456acb646e8e.jpg)

> Please describe how you set that up and what you expect Thunderbird to do.

Despite the multi-addresses selection in Address Book, in the opened composer window I get address(es) set in "Tab-specific Properties" panel...

**Comment by RealRaven2000** [comment]
> > What is "Address book Write action"
> 
> The "Write" button in "Address Book" window:
> ![thunderbird-address-book-multiselection](https://user-images.githubusercontent.com/26068595/107875064-1465f580-6ebe-11eb-9ff6-456acb646e8e.jpg)
> 
> > Please describe how you set that up and what you expect Thunderbird to do.
> 
> Despite the multi-addresses selection in Address Book, in the opened composer window I get address(es) set in "Tab-specific Properties" panel...

Maybe I misunderstand - but I thought the Write button is supposed to set the "To" address. It still makes sense to use a specific From address when we are in a folder that is configured for it - I would think you may want to open ADdress book from a folder to send an email to a person using the identity (from) for that folder? Note that the corresponding "To:" settings does not overwrite the receiver when you write a new Email.

**Comment by RealRaven2000** [comment]
Here is what I think you are doing - correct me if I am wrong

1) you are in a folder that is set up to use a different from address (meaning, if you write an email from here it will select a different identity)

2) You click "Go to the address book" in order to select a recipient
![image](https://user-images.githubusercontent.com/6314674/107875506-4ffdc100-6eb8-11eb-96bb-ebd3da604bfb.png)

3) you end up in Composer writing a new email to the recipient. 

Note: The workflow of setting a different from works best in conjunction with "Copy Sent to Current" which will move your mail straight to the folder - no need to step through the Sent Mail folder in order to manage conversations.

**Comment by RealRaven2000** [comment]
If this overwrites the "To:" address then this is a bug

**Comment by macdeport** [comment]
> overwrites the "To:" address

Exactly that I experienced.

**Comment by RealRaven2000** [comment]
Fix Tb68: [QuickFolders-wx-4.20pre46.zip](https://github.com/RealRaven2000/QuickFolders/files/5977755/QuickFolders-wx-4.20pre46.zip)

Fix Tb78: [QuickFolders-wx-5.3pre35.zip](https://github.com/RealRaven2000/QuickFolders/files/5977754/QuickFolders-wx-5.3pre35.zip)

**Comment by macdeport** [comment]
Fixed 👍

**Comment by RealRaven2000** [comment]
Fixed in 5.3 - released 22/02/2021
