### ISSUE TITLE
Feature request: Option to disable the Update splash screen

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [RealRaven2000/QuickFolders#141]
There should be an option to disable the big here-is-what-is-new screen that appears upon update of the AddOn. Or at least those with paid licenses should be able so to do. Or if there is such an option already then it should be easier to find: I spent five minutes just now unsuccessfully searching (on the Linux version of the program) for such an option.

Thanks.

**Comment by RealRaven2000** [comment]
Good idea! there is currently no such option but disabling it should be possible for QF Pro users. 

I wouldn't want to _default_ to hiding it because there maybe benefits even for them:

- behaviour of the Add-on may be enhanced / changes in ways that impact them
- New functionality can be explained in the user's native language (currently I translate this screen into 17 languages - this is not possible to do with the change log or any of my support website as it is way too much work)
- promotions for renewals / license extensions may also be relevant to the user

having said all that I think opt out of the splash screen should absolutely be possible. I will implement a version here soon and will put the option into the premium features box on the QF Pro tab.

**Comment by fredstluka** [comment]
> There should be an option to disable the big here-is-what-is-new 
> screen that appears upon update of the AddOn. Or at least those with 
> paid licenses should be able so to do. 
An OPTION to avoid showing it perhaps, but please do NOT hide
it by default.  As a paying licensed used of QuickFolders, I really
want to know about the new features when they're added.  I love
the fact that it shows me such release notes automatically every
few days or weeks when a new release occurs.  It's easy enough
to manually close the new tab, clear the popup, etc., once I've
read it.

I also appreciate the effort you put into the styling of the popup
and the multiple languages that you translate it into.  Thanks!

--Fred
------------------------------------------------------------------------
Fred Stluka -- http://bristle.com -- Glad to be of service!
Open Source: Without walls and fences, we need no Windows or Gates.
------------------------------------------------------------------------

**Comment by RealRaven2000** [comment]
> > There should be an option to disable the big here-is-what-is-new screen that appears upon update of the AddOn. Or at least those with paid licenses should be able so to do.

> An OPTION to avoid showing it perhaps, but please do NOT hide it by default.  As a paying licensed used of QuickFolders, I really want to know about the new features when they're added.  I love the fact that it shows me such release notes automatically every few days or weeks when a new release occurs.  It's easy enough to manually close the new tab, clear the popup, etc., once I've read it. I also appreciate the effort you put into the styling of the popup and the multiple languages that you translate it into.  Thanks!

yeah definitely going to be opt-out. and only for people with licenses, because it's my strongest conversion tool at the moment. Gotta live. but I am seriously considering adding a Standard license to get more people contributing. I am just doing modern-style localisation conversion and it's a shitshow. Tons of work, and feels like I am lightyears away from having a web extension / web extension. 

I need to pretty much make all my functions asynchronous and then move the API calls into an experiment (ES6 script) to make the coide reusable and fortify against future changes in Thunderbird. It's a long and winding road...

**Comment by fredstluka** [comment]
Axel,

> yeah definitely going to be opt-out. and only for people with 
> licenses, because it's my strongest conversion tool at the moment. 
> Gotta live. but I am seriously considering adding a Standard license 
> to get more people contributing. I am just doing modern-style 
> localisation conversion and it's a shitshow. Tons of work, and feels 
> like I am lightyears away from having a web extension / web extension.
>
> I need to pretty much make all my functions asynchronous and then move 
> the API calls into an experiment (ES6 script) to make the coide 
> reusable and fortify against future changes in Thunderbird. It's a 
> long and winding road...
>

Doesn't sound fun.  Keep up the good work!  I made another
donation.

What's a "Standard license" vs what you're doing now?

--Fred
------------------------------------------------------------------------
Fred Stluka -- http://bristle.com -- Glad to be of service!
Open Source: Without walls and fences, we need no Windows or Gates.
------------------------------------------------------------------------

**Comment by crablouis** [comment]
fwiw, 

Update popups are valuable to me, and easy to dismiss. I like to know when something's changed. 

Signed, 
Long time paying QF user

**Comment by LinuxOnTheDesktop** [comment]
Axel wrote: '[. .] I think opt out of the splash screen should absolutely be possible. I will implement a version here soon and will put the option into the premium features box on the QF Pro tab.' Thank you. I will not close this issue for the moment.

@crablouis 
Jolly good, but in the text that I have just quoted please note the phrase 'opt _out_'.

**Comment by crablouis** [comment]
<snip> 
> @crablouis
> Jolly good, but in the text that I have just quoted please note the phrase 'opt _out_'.

Yes, I saw that. I just wanted to stipulate the value of maintaining that as the default.

**Comment by RealRaven2000** [comment]
> Doesn't sound fun.  Keep up the good work!  I made another donation. What's a "Standard license" vs what you're doing now?

It's basically a mandatory license / annual payment for all users. A lot of people don't think they need a "Pro" license because they are no "Pros". I have done something similar with SmartTemplates where I had to introduce a Standard License for all users (after a trial period of 28 days) - which obviously gave me many 1 star reviews and lost about 50% of the users. But I absolutely I had to do it because I had to put in a ton of work to support external Stationery (the author of the same titled Add-on had walked away on Tb68) and the Pro Licenses wouldn't have financed that. And as you know I had to bankroll 3,500 bucks for the Tb78 conversion.

So if I introduce this, I will have to be careful. I might just say something like - without a license you can only use the first 10 tabs on the toolbar or other such stupid restrictive stuff - even though I don't like that at all. But I know I will be literally coding for many man-months in order to get closer to a "mail extension" [read: get away from legacy code, such as XUL - now deprecated, XPCOM - only experimental Add-ons are allowed access to XPCOM, which comes with a severe warning when you install it, dtd and properties files as language resources, overlays, and a bunch of other nice but complicated, hacky things] - so really I may not have a choice. Or give up and find another day job. Could concentrate on my music production studio, but it's hard to get off the ground with all the Covid restrictions affecting so many musicians. 

Anyway, no plan to give up. Just want to spread the load a litte more - I don't want a few enthusiasts to bankroll the whole effort. In SmartTemplates a standard license is 5 bucks / year, so QF may be something similar. I still will make it possible to use it for "free as in beer" but need to restrict it somehow in order to give an incentive. I might add a dedicated issue for this endeavour soon. And there should be additional perks for getting a Standard license (such as disabling the splash screen, if people think they have to do it). In a way I can understand because it is disruptive. I try not to update daily or weekly anymore as you may have noticed.

**Comment by fredstluka** [comment]
Axel,

> It's basically a mandatory license / annual payment for all users.
> ...
> after a trial period of 28 days)
> ...
> without a license you can only use the first 10 tabs on the toolbar or 
> other such
> ...
> really I may not have a choice. Or give up and find another day job.
> ...
> 5 bucks / year
>

Sounds good to me.  Obviously, I'd be glad to pay an annual
subscription, since I'm already a Pro subscriber.  And I think
most folks (or enough of them anyhow) would do so.
Especially if you gave them a free trial.  Or limited functions.
Either way, they'll get to experience the value that QF offers
and won't want to give it up.

Also, I think your appeals for cash have been well-written.
They make you seem like a sympathetic character.  One
who's making an honest effort to help his users, and who
seems worth supporting.  Not just someone who's trying to
get rich.

Good luck!

--Fred
------------------------------------------------------------------------
Fred Stluka -- http://bristle.com -- Glad to be of service!
Open Source: Without walls and fences, we need no Windows or Gates.
------------------------------------------------------------------------

**Comment by RealRaven2000** [comment]
Closing this because I implemented not showing the splash screen automatically in QuickFolders 5.7
