### ISSUE TITLE
Thunderbird 60: QuickFolders always offers update to 4.21.2

### ISSUE THREAD

**Issue by MaccabeeY** [RealRaven2000/QuickFolders#145]
You have your version 4.21.2 (the very 2nd to latest version) listed this add on as "good" for Thunderbird versions 60.0 thru 69.0.

However, for a few days now, this addon will not "update" for TB v60.9.1. Would you fix this "bug" one why or another, i.e. change or up the low-end version or test it better.

Either way would you fix it so it does not stay in the TB "Avaiable Updates" list for all eternity, As I'm sure you can understand, I'm gettin' a bit tired of lookin' at it in that list.

Thanks for you attention to this matter.

![image](https://user-images.githubusercontent.com/4692331/115963034-9f2d2700-a4e3-11eb-969a-9e29caac1b43.png)

**Comment by RealRaven2000** [comment]
2 questions:

- What error message are you getting when you click "update now"?
- Which version of QuickFolders is running at the moment?

**Comment by MaccabeeY** [comment]
> 2 questions:
> 
> * What error message are you getting when you click "update now"?  **_--No error message (see pics:  pic above is before clicking "Install Updates"; pic below is after clicking "Install Updates)_**
> * Which version of QuickFolders is running at the moment? **_--4.21.1_**

![image](https://user-images.githubusercontent.com/4692331/115966480-5b421e00-a4f3-11eb-8b43-db6b2264945b.png)

**Comment by RealRaven2000** [comment]
Try to install this hotfix version:

[QuickFolders-wx-4.21.3pre3.zip](https://github.com/RealRaven2000/QuickFolders/files/6370186/QuickFolders-wx-4.21.3pre3.zip)

(github doesn't allow uploading xpi, but you  can just download the zip file above and then **_drag the zip file_** into Thunderbird Add-ons Manager. The bug only affected users of Thunderbird 60 as that is using an older install format (install.rfd) which had a not-matching version number. The Thunderbird Add-ons site (which is inherited from and owned by Firefox) doesn't care about legacy Add-ons anymore so they only look at the version number in manifest.json which leads to this problem.

Notes:
- This version also has a bug fix for "mark folder + subfolders read"
- whenever I upload a Tb60-68 version it "hides" the Tb78 version (because Firefox doesn't care) . So I will need to push both in short succession to avoid Thunderbird 78 users getting an error every time they open Add-ons Manager. It's annoying but Firefox (mozilla) doesn't care for legacy users and they won't patch the site for Thunderbird

**Comment by MaccabeeY** [comment]
I was hoping for merely a version fix.  Thoughtful of you to also include a minor functional fix along with.  The annoying redisplaying in the "Add-ons Manager" in that TB installation is now gone   👍

**Comment by RealRaven2000** [comment]
> I was hoping for merely a version fix. Thoughtful of you to also include a minor functional fix along with. The annoying redisplaying in the "Add-ons Manager" in that TB installation is now gone

Thanks for testing, this fix will definitely go into the next version! At some stage I will have to cut off Thunderbird 60 because there were a few fundamental changes. If you find anything that you think might be TB60 specific please create a new issue for a quick fix!

**Comment by RealRaven2000** [comment]
Fixed in 4.21.3 - pushed to ATN today
