### ISSUE TITLE
Toolbar in single message tab not showing

### ISSUE THREAD

**Issue by PeterW-gif** [RealRaven2000/QuickFolders#174]
Since the update today (version 5.6.5) when I open a single message tab the quickfolders toolbar is not showing. I can invoke it by clicking on 'View; toolbars and then clicking Quickfolders toolbar'. Then it shows Ok, but next time I open a single message tab is has gone again and I have to repeat the above procedure.

**Comment by RealRaven2000** [comment]
It works for me, can you check the following settings in QuickFolders Preferences / Advanced:

![image](https://user-images.githubusercontent.com/6314674/124580131-bd9a9180-de47-11eb-830e-f8049e63d1c0.png)

**Comment by RealRaven2000** [comment]
I may have misunderstood. thought you were talking about current folder bar in message windows. How do you use the main toolbar when in a single message tab? Do you actually use the message tab to open other folders from here? I believe I did some changes in 5.5 back in April (or maybe even earlier) but I guess you weren't updated because of if [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1710359).

Related bugs (affecting single message tabs) / changes:
[issue #84] 

[web extension migration] Improved many functions that worked via accessing the "most recent Thunderbird window" and replaced them with event notifications that propagate to every window. This uses the Notification Tool library and the background script (a mechanism of the new API based "mail extensions" model).

This way all Thunderbird windows (if you work from multiple windows) will be updated correctly when doing one of the following actions. All these now work simultaneously and update in multiple Thunderbird windows:
- ...
- change options of where to display the Current Folder Bar (main window, message tab, single message window)

**Comment by RealRaven2000** [comment]
Here is a test version with a quick fix. To activate the desired behavior (main toolbar remains visible in single message tabs) open config editor, and search fir "hideInSingleMessage", toggle it to false:

![image](https://user-images.githubusercontent.com/6314674/124584112-c68d6200-de4b-11eb-81ee-84e1d10d5653.png)


You can install this prerelease:
[QuickFolders-mx-5.6.6pre3.zip](https://github.com/RealRaven2000/QuickFolders/files/6769230/QuickFolders-mx-5.6.6pre3.zip)

..by downloading the zip file and then dragging it into the Thunderbird Add-ons Manager.

**Comment by PeterW-gif** [comment]
Ok first re your latest email I tried to download the pre-release you sent me the link to but just got an error message saying the site can't be reached, followed by lots of text and ending with "might be temporarily down or it may have moved permanently to a new web address"

Coming back to the problem I reported I first I did check that the settings options you sent me were both ticked before sending the first ticket. This was on my Windows 10 PC but I've just checked it on my MacBook and initially the toolbar was showing on the single message tab there. But then I saw your add-on hadn't been updated on the MacBook, so I updated it and the toolbar then disappeared. So it's definitely something with your latest update.

In more detail then, I have the Inbox tab with the quick folders toolbar displaying Ok. I click on a message which then opens in a new tab but now the toolbar is not showing. I go to 'View, Toolbars, Quickfolders toolbar' which is unticked, so I tick it. Now the toolbar displays Ok and if I then click 'Next' on the main (mail) toolbar to view the next message it remains showing.

But if I then close that tab, go back to the Inbox tab and click on another message, when the tab opens again, the toolbar has disappeared again and when I go to 'View, Toolbars, Quickfolders toolbar' again I find it unticked again.

And this has definitely just started happening since your latest update

I am on the latest version of Thunderbird 78.11.0 on both machines.

**Comment by PeterW-gif** [comment]
Sorry just found that although the webpage showed that error, it has downloaded the zip file. I'll try that and get back to you

**Comment by PeterW-gif** [comment]
Ok done that and initially no difference but when I did as you asked with the Config Editor and changed that value to false, that appears to have fixed it.

**Comment by RealRaven2000** [comment]
> Ok done that and initially no difference but when I did as you asked with the Config Editor and changed that value to false, that appears to have fixed it.

Good. To explain, every tab has a specific type and I deliberately hide the toolbar on tabs where it is irrelevant (e.g. calendar, web pages, options etc.) Single message is an edge case but it seems the "current folder bar" is more useful in this case as it gives options for navigating to the next / previous message and even an option to jump out of the folder:
![image](https://user-images.githubusercontent.com/6314674/124606251-9bfbd300-de64-11eb-89d0-bd5ebbdeac28.png)

That's why the toolbar isn't shown in single message by default. The question is how do you use yours? I assume once I am finished with a single message tab I would just close it (or leave it there and click back on the previous [folder] tab if I wanted to leave it there for later...




. now the question is, do you actually need the toolbar when you are in a single message window? Personally I feel it's only adding clutter .

**Comment by PeterW-gif** [comment]
Yes I understand why there would be no point in displaying it in tabs like calendar, but for a mail item in a single tab I find it very useful. The way I work is my email account is a gmail one that I mirror in Thunderbird using IMAP. So when I start TBird it downloads all the latest unread mails. I then click on the first of these to read it and then decide what to do with it which if an important mail that I want to file I then use the envelope handle to drag to its appropriate storage folder in the quickfolders toolbar. I then click next on the main (mail) toolbar to move to the next unread mail and repeat the process. If I hadn't had this facility before and had to do this filing all from the Inbox tab then I suppose I could have got used to doing it that way, but having had it and preferring to file that way, I suddenly missed it when you did that latest update. So I would request that you keep it there, else I presume each time you or Thunderbird update I'll have to go through the Config Editor to get it back.

**Comment by RealRaven2000** [comment]
> ... I suddenly missed it when you did that latest update. So I would request that you keep it there, else I presume each time you or Thunderbird update I'll have to go through the Config Editor to get it back.

No after I did the patch of 5.6.6pre3 (which honors your setting for  `extensions.quickfolders.toolbar.hideInSingleMessage` ) this will go into the main version. Once you change a setting like this it is stored as "user preference" and won't be overwritten by an Add-on update. The main question is whether I should add a user interface so it can be changed from a checkbox in options.

I am pretty sure hiding the main QF toolbar on single messages like this has already been in place for a long while, but I could be wrong.

**Comment by fredstluka** [comment]
Axel,

> I am pretty sure hiding the main QF toolbar on single messages like 
> this has already been in place for a long while, but I could be wrong.

No, I think Peter is right.  The version of QF that installed itself
today (5.6.5) changed the behavior for me too.

For a few months now, I have been using the TB setting:
- Open messages in = A new tab
instead of the setting I prefer:
- Open messages in = A new message window
The reason has been that, since 4/16/2021 at least (perhaps
always), QF quickMove/Jump/Copy work as desired in a single
message tab, but not in a single message window.
See details in https://github.com/RealRaven2000/QuickFolders/issues/138

As of today (5.6.5), the QF toolbar is no longer displayed in a
single message tab, so the QF Pro quickMove/Jump/Copy
shortcut keys no longer work in a single message tab.

I see the following behavior also, all exactly as Peter said:

- I can cause the QF toolbar to appear in a single message tab
    via:
     - View | Toolbars | QuickFolders Toolbar

- I have to do the above manually for each single message tab
    that I open

- I installed the zip file: QuickFolders-mx-5.6.6pre3.zip 
<https://github.com/RealRaven2000/QuickFolders/files/6769230/QuickFolders-mx-5.6.6pre3.zip>
    and it had no immediate effect

- As you directed, I used the TB Config Editor to change this
    value from true to false, and it solved the problem.  The
    QF toolbar now appears in each single message tab as it
    did before QF 5.6.5.
    - extensions.quickfolders.toolbar.hideInSingleMessage = false

Other notes:

- This is probably not relevant, since you asked before you
    realized that the toolbar we're talking about the main QF
    toolbar, not the "Current Folder Toolbar", but in case you're
    interested...
    I have all 3 options checked in QF Advanced options:
    - Display the Toolbar
    - Toolbar in Single Message Tabs
    - ...also in Single Message windows

- I did NOT get the error that Peter reported when downloading
   the zip file.

- I'm using:
    - TB 78.11.0
    - MacBook Pro (16-inch, Intel CPU)
    - macOS 11.1 (Big Sur)

- I use a TB single message tab all the time (until the day QF
    is hopefully updated to work in a single message window).
    I open Inbox, see a new message, open it in a single tab,
    read it, reply, etc.  Then I either delete it to see the next
    message in the same single message tab, or use QF quickMove
    to file it away in a different folder and see the next message
    in the same single message tab.  I may keep that same tab
    open for dozens or messages or more, as I go though my
    Inbox.  I'm using it like the TB preview mode, but in a
    separate tab that doesn't show the subject lines of other
    messages, so more screen space is available for the body
    all the one message.

- You say the "current folder bar" is more useful in a single
    message tab, but it does NOT offer me a way to file messages
    away in other folders via the QF Pro shortcut key Shift-M.
    For that, I need the main QF toolbar.

- For me, the QF toolbar is never just "clutter" because it allows
    me to use the QF Pro shortcut keys

- I suggest you change the default value to false, because that
    gives me the same behavior by default that I've had before:
    - extensions.quickfolders.toolbar.hideInSingleMessage = false

- I also suggest you add a UI to change the value to true if you
    think people will want a way to change it.  For myself, I plan to
    always leave it false.

Thanks, as always, for the quick response and great support!
--Fred
------------------------------------------------------------------------
Fred Stluka -- http://bristle.com -- Glad to be of service!
Open Source: Without walls and fences, we need no Windows or Gates.
------------------------------------------------------------------------

**Comment by crablouis** [comment]
FWIW, I'm running TB 78.11.0 (32-bit) on tehe auto update channel, and QF 5.6.5 of today. 

In this config here, the QF Options setting is persistent. QFToolbar in new message window and/or tab.

Selecting and de-selecting the options are both persistent and consistently implemented through multiple TB sessions.

**Comment by PeterW-gif** [comment]
Firstly to thank RealRavn2000 for his quick attention to this issue and the fix he sent me which he told me will be made permanent.
Second to confirm that the problem was caused by the latest update to Quick Folders. Having first found it on my Windows 10 64 bit PC I then checked it on my MacBook running OS11. I started Thunderbird, and clicked on a mail to open it in a single tab. At that point the toolbar was displaying. I then opened a fresh tab and checked my add-ons and found that Quick Folders had not yet been updated on the MacBook. So I then updated it and then clicked again on the same single tab email (which had been left open) and now the quick folders toolbar was no longer displayed.
Thirdly RealRaven asked about "whether I should add a user interface so it can be changed from a checkbox in options". This is already there and works with the fix. Go to Quick Folders Settings, Advanced Tab, and deselect 'Toolbar in Single Message Tabs' and the toolbar disappears, select it again and the toolbar comes back. As far as I can see nothing more needed other than to make the fix permanent.

**Comment by PeterW-gif** [comment]
Sorry on that third point, I just noticed it is only the 'Current Folders Toolbar' that toggles with that command, The actual folders bar remains, so yes an extra option to remove that would be required - if anyone really didn't want it to display on single message tabs

**Comment by RealRaven2000** [comment]
To start with I have changed the setting to default to `false` (don't hide the toolbar in single message tabs). I had an older setting to hide QF "when not needed" that was long defunct (it is now always doing this) - which prevents the toolbar from being shown in tabs that do not show any mails (calendar, options, Add-ons Manager etc.)

The setting in config was called `extensions.quickfolders.toolbar.onlyShowInMailWindows` and there is even a (superflous) UI - a checkbox that doesn't do anything here on the General settings tab:

![image](https://user-images.githubusercontent.com/6314674/124742468-aa092c80-df14-11eb-9502-341ffc5e683e.png)

So this is where I am going to put a new checkbox for "hiding QuickFolders in single message tabs" instead. I also had to add a new notification event listener so that you can get instant feedback when changing the setting while (a) Thunderbird window(s) is / are open with a single message tab showing. For test version see below:

[QuickFolders-mx-5.6.6pre17.zip](https://github.com/RealRaven2000/QuickFolders/files/6776751/QuickFolders-mx-5.6.6pre17.zip)

**Comment by PeterW-gif** [comment]
Just downloaded this and yes that seems to do the job, toggling the quickfolders toolbar on and off in the single message tab. It does leave the Current Folder bar displaying but this can also be turned off in the Advanced tab as I outlined above. Many thanks again

**Comment by RealRaven2000** [comment]
Fixed in Release 5.6.6
