### ISSUE TITLE
redux issue:  Thunderbird 60: QuickFolders always offers update to 4.21.2 (actually now it's in 4.22.2)

### ISSUE THREAD

**Issue by MaccabeeY** [RealRaven2000/QuickFolders#180]
The issue I reported back in Apr. '21 has crept back in with the release of 4.22.2, see [Thunderbird 60: QuickFolders always offers update to 4.21.2](https://github.com/RealRaven2000/QuickFolders/issues/145).

**Comment by RealRaven2000** [comment]
4.22.2 was disabled for a few days so that 5.6.6 could be released first, but it is enabled now as last official version on Thunderbird 68 (and older). So I have no idea why and older version is being offered. internally the version number is correct, and the compatibility on ATN, too:

![image](https://user-images.githubusercontent.com/6314674/125678721-f0337184-e4d5-4484-ac4f-8ed7ebf4f3f4.png)

**Comment by RealRaven2000** [comment]
```
The install.rdf of 4.22.2 also has the correct version number:

<?xml version="1.0"?>

<RDF:RDF xmlns:em="http://www.mozilla.org/2004/em-rdf#"
         xmlns:NC="http://home.netscape.com/NC-rdf#"
         xmlns:RDF="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
		 
  <RDF:Description RDF:about="urn:mozilla:install-manifest"
   em:name="QuickFolders"
   em:id="quickfolders@curious.be"
   em:creator="Axel Grude"
   em:description="Bookmark your favorite mail folders in Thunderbird."
   em:iconURL="chrome://quickfolders/skin/ico/quickfolders-Icon.png"
   em:icon64URL="chrome://quickfolders/skin/ico/QF64x64.png"
   em:optionsURL="chrome://quickfolders/content/options.xul">
    <em:type>2</em:type>
	  <em:version>4.22.2</em:version>
```

**Comment by RealRaven2000** [comment]
I checked the error log it says somethiung about inbvalid application entries in install.red.

Please try this test version:

[QuickFolders-wx-4.22.3pre1.zip](https://github.com/RealRaven2000/QuickFolders/files/6818475/QuickFolders-wx-4.22.3pre1.zip)

I removed 2 of the `<em:targetApplication  />` tags in this one. I had to removed SeaMonkey and Postbox compatibility because they were so far behind.
