### ISSUE TITLE
Tabs are black from position 11 without license

### ISSUE THREAD

**Issue by vlanel** [RealRaven2000/QuickFolders#193]
Hi everyone

since the last update many of my tabs are suddenly black ?!

how can I change this?
![black tabs](https://user-images.githubusercontent.com/88842234/129216732-c8bbb853-1904-429e-957d-d3812b82f252.jpg)

**Comment by RealRaven2000** [comment]
> since the last update many of my tabs are suddenly black ?!

this  behavior is by design - due to the new 3-tier licensing system. There are now 3 ways to use QuickFolders, unpaid, QuickFolders Standard and QuickFolders Pro. The introduction of the Standard license is discussed and documented at issue #187. Standard allows using 25 tabs with full functionality whereas the unpaid version allows 10, QuickFolders Pro is unlimited. The complete feature comparison can be [read here](https://quickfolders.org/premium.html#featureComparison).
 
> how can I change this?

You can either buy a [Pro License](https://sites.fastspring.com/quickfolders/instant/quickfolders?referrer=github), a [Standard license](https://sites.fastspring.com/quickfolders/instant/quickfoldersstandard?referrer=github) or roll back QuickFolders to the previous version (5.6.6). If you decide for the later, don't forget to disable automatic updates in Add-ons Manager.

Note that **only QF 5.7 is compatible with the future version of Thunderbird (91)** - the [change set in QuickFolders](https://github.com/RealRaven2000/QuickFolders/compare/5.6.6...5.7) is about 5000 changes, to make it compatible and add the latest features - which is what the licenses pay for.

**Comment by vlanel** [comment]
Hi,

this is really annoying, these plugins which are free and then you remove features and ask users to pay. not nice!

**Comment by RealRaven2000** [comment]
> this is really annoying, these plugins which are free and then you remove features and ask users to pay. not nice!

These plugins are "free" as in freedom - completely 100% open source and can be changed by the user to their needs, and all changes are done in public and discussed with my users. I have been working on QuickFolders for 12 years, and had to hire an external developer last year for the conversion to Thunderbird 78, which cost me $3,500 (he only charged €25  / hour which is not much in software) - this was funded by QuickFolders Pro licenses and I had to put up an annoying Splash screen in order to make that money back. 

Every 4 weeks (changed from 6 weeks last year), Mozilla releases a new version of the [Mozilla-Central](https://searchfox.org/mozilla-central/source/) platform code that Thunderbird is built upon - they then have to integrate the changes into their own code base. On top of that they have mail specific code ([comm-central](https://searchfox.org/comm-central/source/)) they have to develop and fix. Firefox (which is based on the same code base) got rid of legacy add-ons in favour of "web-extensions" altogether, which means: no more toolbars, and only certain approved points (APIs) for programming which are permissions based. That's when many 100s of Add-ons stopped working.

Thunderbird rebranded the concept of "web extensions" to "Mail extensions". Bu they were "nice" and decided to not completely cut us off, and allowed a transition model so called "mail extensions with experimental APIs"  where we are still allowed full access to the underlying code (which is undocumented, unguaranteed and hacky) while developing our own experimental APIs in order to supply all the functionality that they have taken away from us. So we have to constantly work (and remember they can break every 4 weeks and are ABSOLUTELY GUARANTEED TO BREAK once a year when they integrate all major changes into the new ESR period. 

If I do nothing, the Add-on stops working - that's exactly the reason why 5.6.6 will fail in Thunderbird 91. So I forced to work on my Add-ons every day, making sure they keep working and inventing new features. I am also supporting my users for free and help them to use their Email more efficiently. And I am answering concerns like the one you have submitted here. It's not easy. If my plugin was an app (like a windows exe program) there would be no such hassle, as Operating Systems do not change over 10s of years. So it's easy to make a software (app) once and then sell it and the user can use it forever. 

With Add-ons this is not the case. There are a lot of functions that are simply not possible with a "mail extension" for instance writing a file to a user determined location or making your own toolbars to name just two. I am constantly working with Thunderbird Core developers to convince them to allow more functionality using the new API based system so QuickFolders won't stop working.

I get that you don't want to pay for Software, because you probably think that large corporations or advertisements pay for that work, but this is not the case in the Add-ons world. You may also think that it's easy to program such an Add-on, I invite you to look at the changes and [code base of the last 12 years](https://github.com/RealRaven2000/QuickFolders/tree/ESR78). 

If you really cannot afford the 5bucks in order to fund this work and want to rely on others to pay for you, why don't you simply send me an email and ask for a free license key? It's no problem for me to make you one, I understand that it's not easy nowadays. But I have to stay on this course in order to protect the Add-on so that it may exist in the future, I don't want to walk away from it and abandon it (I use it every day) but I cannot work 5 hours / day for free. I also want to make sure many people can use it so I translate every text (many hundred strings) into 19 different languages - I don't hire external translators to keep the cost low. So I can make an exception for you but I won't change my monetization for the whole project. 

The licenses have only become cheaper over the years because I did a lot of work convincing more people to contribute and spread the load - once all the functions needed are support by APIs I can hand out permanent licenses because Mozilla promises that they should stay largely the same, which would be a great relief to me. At the moment I have to always expect that something stops working because of their changes, and only through the licenses will I stay motivated to do this quickly and efficiently. Hope you understand now.

Hit me up for a free license if you like, you can mail me directly from the support tab. It never hurts to ask :)

**Comment by RealRaven2000** [comment]
> Every 4 weeks (changed from 6 weeks last year), Mozilla releases a new version of the [Mozilla-Central](https://searchfox.org/mozilla-central/source/) platform code that Thunderbird is built upon - they then have to integrate the changes into their own code base. On top of that they have mail specific code ([comm-central](https://searchfox.org/comm-central/source/)) they have to develop and fix. Firefox (which is based on the same code base) got rid of legacy add-ons in favour of "web-extensions" altogether, which means: no more toolbars, and only certain approved points (APIs) for programming which are permissions based. That's when many 100s of Add-ons stopped working.

Just to explain this a little better:

Thunderbird (and Firefox) updates silently every 4 weeks with maintenance updates (including only important stability and security fixes) without the user noticing - we are on 78.13 at the moment. But every year all changes are integrated, so Thunderbird [version 91.0 has just been released](https://www.thunderbird.net/en-US/thunderbird/91.0/releasenotes/) and 91.1 will probably be automatically pushed out to about 10% of users (roughly to 2 million people). This method is called ESR (annual Extended Service Release) - the Thunderbird team actually worked all year on beta versions 79, 80, 81 etc in order to integrate all these changes, whereas you as end user on the release channel only get minor version bumps (78.1, 78.2 etc.). 

This is when all the "plugins that are free" will break again and many users will be disappointed and  angry and write 1star reviews to the developers who do not monetize. We had a major outage last year because the changes were so big that I couldn't program them on my own, it was just too much work. When I started I wasn't even sure whether I would be able to still have all the functionality I added - it took a lot of conversation with the Thunderbird Core team as well to find out how and what was possible. I am really thankful that they didn't decide to do it like Firefox and just cut off all access to the scriptable JavaScript parts, because that would have killed many more Add-ons. 

You can see now that there are other developers writing new / updated versions of Add-ons that worked until Thunderbird 68 but they are also considering financing that work. Once you hit several 1,000 lines of code, it becomes really complicated real fast. Unfortunately the Add-ons site has no built in method of asking for license payments, unlke iTunes and google play where such things a built in - so every developer has to find their own method of financing the work, which is actually very difficult and risky to develop. Thankfully I got advice from Kent James who wrote many commercial Add-ons (one of them is FiltaQuilla which I took over and keep developing free of charge) and suggested to use [fastspring](https://fastspring.com/) for handling these transactions; also license validation is HARD - it is still a lot of work - that's another reason you do not see many Add-on author do it and see their Add-ons not working after a while. 

So please consider that what you think should be "free" was always financed by other people, either via donations or by just working unpaid many hours just for the love of it. Which I did for many years, it just got too much to do it for free.

**Comment by fredstluka** [comment]
Axel,

Thanks for taking the time to explain the licensing situation so
thoroughly.  Personally, I'd never have had the patient to do
that.  I find it difficult to deal with unappreciative people who
complain that something they paid nothing for is evolving to a
lightly paid model.

And as you pointed out, QuickFolders is still FOSS (Free and
Open Source Software), so any user who doesn't want to pay
$5/year, can download the source and build/maintain his own
copy.  If any do so, I suspect they'll come to appreciate how
much work it is to keep it working as Thunderbird changes
over time.  And will likely abandon the effort and happily pay
the minimal licensing fee instead.

I hope you'll keep the licensing fees high enough to justify the
time and effort you continue to put in to QuickFolders.  If not,
it's inevitable that you'll eventually abandon it, and all of us
users will lose a valuable tool.

Keep up the good work!
--Fred
------------------------------------------------------------------------
Fred Stluka -- http://bristle.com -- Glad to be of service!
Open Source: Without walls and fences, we need no Windows or Gates.
------------------------------------------------------------------------

**Comment by vlanel** [comment]
either it's freeware or not...
takeing away features and asking for money is a "no go" (unless you are whatsapp or another of these big commercial companies)

**Comment by RealRaven2000** [comment]
That's just your opinion.

I made a new version for Tb91 with ny work. you are free to use the older
versions forever if you prefer them.

QF isn't freeware. It got more sophisticated and harder to fix in the 12
years I worked on it because it was paid for by licensed users. if it
breaks every year because Mozilla changes everything, who is supposed to
work on it for weeks unpaid?  guess why do many add-ons went away in Tb78 -
because nobody could afford to hire a developer.

I paid  external devs 3000 Euros for rewriting and another 600 for
migrating from the "free as in beer" mozdev.org server which had
deteriorated over the years (many outages and no funds to replace or
service it) - paid for by licensees. other Add-ons stopped working and
didn't have homepages anymore.

Also when you go to petrol station, do you expect the coffee to be free?
