### ISSUE TITLE
Feature request Pro version: History of 10 recent quickMove folders

### ISSUE THREAD

**Issue by kwoot** [RealRaven2000/QuickFolders#207]
Hi,
As a user I like to see a small history of recent quickMove folders I used.

Background to this. When processing my daily inbox I often move messages to a few different folders. If I press Ctrl=M on a message I see my last selection, but I really like to see a list of my 10 most recent folders. Then I can simply use an arrow key to select one of those instead of typing in part of its name again, and press Enter to have it moved.

Would be a lovely addition to a very nice plugin.

Regards,
Jeroen Baten

**Comment by RealRaven2000** [comment]
Could be an additional option, we could call it "quickMove History >" - it would not include anything from quickJump and wouldn't be available by default as I am trying to keep this menu as uncluttered as possible for the "average" users. The question is, where should it be positioned? My preference would be to not put it on the "suggestions" menu because once you type anything (and that's the only time I show the menu) you want the best matches on the top? 

It might be better to put it onto the "right-click" menu on the icon - even though it would require an extra click (I would see looking at historic items as an exception):

![image](https://user-images.githubusercontent.com/6314674/135599471-4e02c384-a6dc-4f49-9744-5998ec2b3c84.png)

But I guess having it "keyboard only" you would want to be able to access it without mouse interaction. So the most important question - where to place this? Should it show up before you type and then be replaced with the matching suggestions once you enter a letter? It feels like that would be the least intrusive method...

**Comment by kwoot** [comment]
Well, you're the application expert, but I think you're on the right track. 

Indeed, if possible I prefer keyboard interaction with optional mouse interaction. I could do a Ctrl+M, see the history, use arrow keys + Enter, or a mouse click, to select folder in history to move the message to a folder. 

Also Ctrl+Click in message list pane to select multiple messages and then Ctrl+M to move those to the same folder, selected as described above.

Thanks for the quick reply and really looking forward to this!

**Comment by RealRaven2000** [comment]
This is going to take a while to develop as I need to create the storage for the last 10 items first before I can even think of generating the menu. I have pinned it to the top 3 issues though, I think it could quite valuable to QuickFolders Pro users. I will upload related prerelease versions here so you will be notified automatically when something is ready to test.

**Comment by kwoot** [comment]
No pressure, really. Good luck with your work.

**Comment by jaysmithgit** [comment]
Axel, this feature is something I have been wanting, but did not do a good job of explaining what I wanted.  I think it is super-important.  I am a subscriber to the Pro version.

Thanks for considering the possibility of adding this feature.  For me, this nearly completes the feature set that is most valuable to me.

In reply to the discussion up to this point...

- Rather than selecting a "hard" quantity, such as 10, allow this value to be user-configurable, with the understanding that a larger value may slow the program.  If it must be a "hard" number, I suggest 20.

- It is extremely important to me that such operations may be done via the keyboard: Type some keystroke or keystroke combination to do the tasks of "jump to" OR "move mail to", then use keyboards up/down arrow keys to select the desired target, then hit return to execute the operation.  (And probably ESC to abort the operation.)  Using the mouse or other pointer device just takes extra time and is not as accurate (for me).

- In my work, I very regularly use the "jump to" AND the "move mail to" for the same target. It would be very helpful to me if BOTH are in the SAME remembered list, with the most recently accessed being the first one to which the selection focused can be moved.

- Please be sure that regardless of whatever text (i.e. some text of the path followed by a slash OR the terminal folder name) is typed to originally "jump to" or "move mail to" a folder, that the full path is accessible by using the remembered list.  [This may be a moot point in the current version, but I mention it because in QF 5.5.2 the "Recent Folders" folder name is not accessible by repeating the action IF "some text of the path followed by a slash" had been typed to jump to or move mail to that target.  (In QF 5.5.2, if the _terminal_ folder was typed, then it IS accessible for repeated use).]

Thanks,

Jay

**Comment by fredstluka** [comment]
Yeah, this would be useful for me also.

--Fred
------------------------------------------------------------------------
Fred Stluka -- http://bristle.com -- Glad to be of service!
Open Source: Without walls and fences, we need no Windows or Gates.
------------------------------------------------------------------------
