### ISSUE TITLE
Theming problem: text of tabs in Options screen illegible in Thunderbird 91

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [RealRaven2000/QuickFolders#209]
Thunderbird 91.1.2 x64
Windows 10
QF 5.7.2
Thunderbird theming options: dark mode enabled, as shown (though not very clearly) in this screenshot:
![image](https://user-images.githubusercontent.com/47056543/136235263-d692b9ea-dac5-4e1a-9f74-3e351ce33c26.png)

I'm seeing this:

![image](https://user-images.githubusercontent.com/47056543/136234159-949bc6ae-b3b0-418f-8524-375f73faeaec.png)

The text for icons is barely visible.

**Comment by LinuxOnTheDesktop** [comment]
Addendum: if I tell Tbird to use the 'system theme', then the problem does not go away.

**Comment by RealRaven2000** [comment]
This one's a bit finicky - had to try a few things to make it compatible with most (not saying all) light weight themes:

![image](https://user-images.githubusercontent.com/6314674/136256418-2bd6aeea-8090-4a08-872f-c0be9cc8c41b.png)

Test version: 
[QuickFolders-mx-5.8pre16.zip](https://github.com/RealRaven2000/QuickFolders/files/7296118/QuickFolders-mx-5.8pre16.zip)

For the "preview area" on the layout (bling) page I changed the background image alignment to left rather than right, but htere are still some issues with the colors of the dropdown menus for color choices.

**Comment by LinuxOnTheDesktop** [comment]
The pre-release version seems to solve the problem. Good stuff!

**Comment by RealRaven2000** [comment]
I also fixed the dropdown colors. I couldn't find this issue because it was closed by @LinuxOnTheDesktop - which I generally do not do before releasing the official version, so I accidentally opened a new issue #212. This one also addresses the color palette dropdowns on the preview pane on "bling my tabs":

[QuickFolders-mx-5.8pre49.zip](https://github.com/RealRaven2000/QuickFolders/files/7337742/QuickFolders-mx-5.8pre49.zip)

**Comment by RealRaven2000** [comment]
...and one more fix - to include the dropdown for theme selectiopn on "bling my tabs":

[QuickFolders-mx-5.8pre61.zip](https://github.com/RealRaven2000/QuickFolders/files/7338447/QuickFolders-mx-5.8pre61.zip)

To install this prerelease download the zip file and drag into Thunderbird Add-ons Manager. When testing you might have to re-open the options dialog between theme changes (although it largely updates in realtime)
