### ISSUE TITLE
'Show Splash screen' menu item would be better called 'Show splash-screen now'

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [RealRaven2000/QuickFolders#215]
The inclusion of the word 'now' is the important part of the proposed change. Including that word would help disabuse the user of an impression that at present she is liable to have. That likely misconception is: clicking that menu item will bring up a way of toggling an _option_. (Yes, 'QuickFolder Options' is another entry in the same menu. It is good though if one can use a menu merely by glancing at it.)

QuickFolders 5.8.1 on Windows 10 and Thunderbird 91.2.0.

**Comment by RealRaven2000** [comment]
I do prefer the old wording, but I could add the ellipsis "..." to signal that this will open a new Window - this is a common Windows way  of signalling that there is more information to come. Also it will make it very clear that this isn't a toggle. For me it is very important that the user gets a chance to read this (fully localized) information as it is my only persistent way of informing the user of any news.

These are: important changes (not complete) in the software and discount prices for licenses if available at the moment - my monetization relies on the later. Quite happy that I got rid of the "forced splash screen" by adding the signal blue on the QuickFolders label (News button). You can trust me that there is still a number of users who never see this button and never click on it because they are simply overwhelmed by the Thunderbird User Interface - I am very likely never to get any business transation with them other that free support. :)
