### ISSUE TITLE
Tabs are displayed vertically instead of horizontally

### ISSUE THREAD

**Issue by Vacoas** [RealRaven2000/QuickFolders#228]
Hello,

I am currently using the following  :
- Windows 11 21H2 Build 22000.348
- Thunderbird 91.3.2
- QuickFolders 5.8.3

For the last 3 months, the tabs have sometimes been displayed vertically instead of horizontally :
![Horizontal](https://user-images.githubusercontent.com/45902444/143770136-37f9c333-e30d-42ac-97bb-e4ca33033c08.png)
![Vertical](https://user-images.githubusercontent.com/45902444/143770145-c3d058ec-cf5d-4e0d-8bc6-07ca0699ef27.png)

It started happening when I was still using Windows 10 but already using TB91. I can't say precisely what version of TB and QuickFolders the problem started with but I tried at the time to go back to previous versions but the problem still occurred.

The problem occurs either when TB is started or when QuickFolders is disabled then enabled. 
It can then occur many times in a row (up to 10 or 12) then stop occurring.
It started happening when I was still using Windows 10 but already using TB91. I can't say precisely what version of TB and QuickFolders the problem started with but I tried at the time to go back to previous versions but the problem still occurred.

The problem occurs either when TB is started or when QuickFolders is disabled then enabled. 
It can then occur many times in a row (up to 10 or 12) then stop occurring.

I thought it could be linked with CPU load but it does not seem to be the case.

The attached console export file contains information after performing the following steps :
- Starting TB
- Tabs displayed vertically
- Disabling QuickFolders
- Enabling QuickFolders
- Tabs are displayed vertically again
[console-export-2021-11-28_11-57-29.txt](https://github.com/RealRaven2000/QuickFolders/files/7613642/console-export-2021-11-28_11-57-29.txt)

I can provide further information if necessary.

Regards.

**Comment by RealRaven2000** [comment]
So I understand you have the problem whenever you start Thunderbird (or QuickFolders) and not in the middle of running it.

Thanks for including the error log, can you do me a favor and generate it again, with timestamps disabled - that's going to make it easier to read.

The problem must be related to CSS rules - either not loading at all or being overwritten (more likely) by another Add-on or your theme. What other Add-ons are loaded? Are you using the default theme?

The best way to find a CSS problem is by using inspector (Ctrl+Shift+I). With inspector enabled click on one of the tabs to view its rules, then on the right-hand side, select the Layout tab:

![image](https://user-images.githubusercontent.com/6314674/143772465-08e8e372-bc13-46f7-9534-11a1e64bd68e.png)

I would expect any tab to have a display falue of "inline-block". If it is something else (e.g. block) then this would be one root cause. ALso what about the container boxes (the toolbar or box):
![image](https://user-images.githubusercontent.com/6314674/143772552-22b94b55-123f-4f6b-8a17-b35ea3539222.png)

do they take up the width of the whole window or are they displayed on the left hand side of the other 3pane elements (folder tree, mail list, preview pane). What is select in View / Layout (Classi / Wide / Vertical) and is the Folder tree displayed?

**Comment by Vacoas** [comment]
Thanks for your suggestions and your requests.

I have not been able to reproduce the problem since yesterday.

I'll disable the timestamps next time I provide an error log.

The problem has already occurred with all other add-ons disabled. 
I am using the default theme.
I use the Classic layout.
When the problem occurs, the tabs are displayed vertically and nothing else is displayed on the line (folder tree, mail list, preview pane).

I sudenly remembered that even though all the add-ons were disabled, I had forgotten to remove CSS files related to one of the add-ons (userChrome.css and userContent.css in the <profile>/chrome folder). The add-on is 'DeepDark | Emerald Edition'

I'll now try to reinstate that particular add-on with and without its CSS files and see if I can reproduce the problem.

**Comment by RealRaven2000** [comment]
A copy of your userChrome.css may also be very helpful in this case!

**Comment by RealRaven2000** [comment]
Closed the issue for now - feel free to reopen when you have a way to reproduce the problem.
