### ISSUE TITLE
[feature request] Allow QF to use a non-default identity for licensing

### ISSUE THREAD

**Issue by tangodev** [RealRaven2000/QuickFolders#238]
Hello,

I've been using a licensed version of QF and it really helped my productivity with Thunderbird. There's one thing however: I use a different identity for my purchases, so I had to use that one as my default one.

**Would it be possible to bind the license key to a non-default identity?**

**Comment by jaysmithgit** [comment]
Hi Tangodev,

I also use a licensed (Pro 5.5.2) version, with both multiple identities and multiple accounts, but I am not having problems that you seem to be having.

However, you don't say what problems you are having.

- My license is bound to my "primary" email address (main account) for which I originally configured TB.

- Then I added an *additional identity* to the main account so I can send and reply using that additional identity. (We use IMAP with several users, thus I am often replying to emails sent to email addresses other than my primary email address.)

- Furthermore, I added *additional account*, on a completely different IMAP server physically located on the other side of the country,  with a completely different email address (domain is different, everything is different). That account has it's primary email address, plus another identity (on my local system) which I added.

In that environment, my version QF 5.5.2 works perfectly fine in all functions with all identities and accounts. I can move to / file into any of the four total identities, spread across two accounts.  (Yes, the QF and the TB is from about year ago, but I have to be very deliberate about upgrading to new TB and to new QF because this is a mission critical application.)

My understanding a year ago was that as long as the QF licensed email address is the same as one (not sure if it has to be the primary) of the accounts, then QF works for everything on that Thunderbird instance.  Perhaps this has changed in the last year?

I hope that helps.  I am not sure what problems you are experiencing.

Jay

**Comment by RealRaven2000** [comment]
I've been using a licensed version of QF and it really helped my productivity with Thunderbird. There's one thing however: I use a different identity for my purchases, so I had to use that one as my default one.
> 
> **Would it be possible to bind the license key to a non-default identity?**

@tangodev  - there is a way to do this in exceptional cases, but I am not documenting this officially to avoid abuse of the feature. Simply send me an email and I will tell you how to do it. 

The same rule applies to anybody else who wants to do this. primary identity works for most users, it also works even with an old account that doesn't receive emails anymore - as you know you can have multiple accounts in the same TB profile.

> In that environment, my version QF 5.5.2 works perfectly fine in all functions with all identities and accounts. I can move to / file into any of the four total identities, spread across two accounts. (Yes, the QF and the TB is from about year ago, but I have to be very deliberate about upgrading to new TB and to new QF because this is a mission critical application.)

@jaysmithgit - the current version of QF should also work fine with Thunderbird 78, but you can always easily roll back QF versions without breaking anything. 78 and 91 are actually very similar (the big change was from 68 to 78), but 91 has some regressions around moving folders which hope they fix soon.

Axel

**Comment by tangodev** [comment]
Hello,

@jaysmithgit thanks for the info.

@RealRaven2000 thank you for the information. I had a feeling it may be an anti-tamper thing. Don't worry, this was a minor nitpick from me. As far as I'm concerned, the case is closed.
