### ISSUE TITLE
"=" key of QuickMove/Jump "Enter" won't operate on folders that have subfolders...

### ISSUE THREAD

**Issue by fredstluka** [RealRaven2000/QuickFolders#254]
Axel,

I love the new "=" key of QuickMove/QuickJump.  But one minor problem.  When I want to move again to a folder that has subfolders, it shows me the folder, but with a ">" and allows me to navigate to the list of subfolders.  So far, so good.  But if I want to specify the parent folder itself, I can't find a way to do it with the keyboard.

For other recent folders, I can use the up/down arrow keys to move to the one I want and then hit Enter.  But for recent folders that have subfolders, Enter does not choose the folder.  Instead, it shows the list of subfolders.

There seems to be no way to choose the parent folder itself except by abandoning the keyboard and clicking with the mouse.

Since right arrow can be used to show the list of subfolders, I don't need Enter for that.  I'd prefer that Enter be a way to choose the parent folder.  

Alternatively, add an entry to the list of subfolders to indicate the parent itself.  That's what happens with the native TB "Move To" menu.

Thanks!
--Fred

**Comment by RealRaven2000** [comment]
It looks like the missing command handler for "Enter" is an effect of the way the (conventional) recent folders menu is built: it is also not present there, as originally there was no keyboard support planned for that. So I need to fix the problem on that level - this is done in function `QuickFolders.Interface.addSubFoldersPopupFromList()`

**Comment by RealRaven2000** [comment]
Here is a question, should the quickMove / quickJump  "Recent" folder list actually display subfolders at all? It seems like unnecessary clutter. 

Also: when we enter a search term the only way to get subfolders is by entering "/" or ">" at the end of the string
![image](https://user-images.githubusercontent.com/6314674/161424620-d96944b3-7486-4436-a06e-884a1dcb21d3.png)

**Comment by RealRaven2000** [comment]
Here is an alternative version - instead of adding the complexity to the recent folders menus I am simplifying by not adding subfolders to the recent folders menu:

[QuickFolders-mx-5.9pre5.zip](https://github.com/RealRaven2000/QuickFolders/files/8404431/QuickFolders-mx-5.9pre5.zip)

I think this is actually a better solution as a quick jump / quick mail move to a recent location will usually not require investigating a lot of subfolders. At least this is my theory. It simplifies the menu and adds easy keyboard support for the Enter key. Allowing enter on folder popup nodes is actually not trivial as the menu is built by the system and puts its own event handler there for popping up the child menu.

To get the old behavior back with this version, one can right-click "Display Recent folders tab" and then set the option `extensions.quickfolders.recentfolders.subfolders=true`
![image](https://user-images.githubusercontent.com/6314674/161426731-cd5f6658-4249-444f-924e-cd79f93afcc1.png)

**Comment by fredstluka** [comment]
> Here is a question, should the quickMove / quickJump "Recent" folder list actually display subfolders at all? It seems like unnecessary clutter.

I agree.  No need for subfolders.  --Fred

**Comment by fredstluka** [comment]
Axel,

I tried the new 5.9pre5 version.  Works perfectly.  Thanks!

--Fred

**Comment by RealRaven2000** [comment]
Implemented in 5.9.1 - Published 05/04/2022
