### ISSUE TITLE
Recent folders on Navigation Bar (Current folder toolbar) outdated when dragging emails

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/QuickFolders#262]
The recent folders button on the center of screen sometimes doesn't show the latest recent folders when a mail is dragged to it. It should always be generate freshly whenever an item is dragged to it even if it takes a little longer...

**Comment by RealRaven2000** [comment]
Here is a test version that should enforce building a fresh "recent folders" dropdown every time:

[QuickFolders-mx-5.10pre3.zip](https://github.com/RealRaven2000/QuickFolders/files/8571981/QuickFolders-mx-5.10pre3.zip)

To install this preview version, download the archive file and then drag it into Thunderbird Add-ons Manager (without unpacking).

**Comment by QFUserPS** [comment]
Thanks for the quick and efficient support

While the solution proposed in the comment above perfectly works out, I noticed that the bug (i.e. getting a recent folder list that is different from the latest one) reappeared as soon as I moved a mail to a folder via the QuickMove function. Since I used QuickMove, the recent folder list I get when trying to drag-and-drop an e-mail to the recent folder list of the current folder tab is frozen, i.e. it is the last one (that was correct) before I did the QuickMove action. Moving any e-mail to any folder, e.g. over tabs, updates the recent folder list correctly, but not any more the one proposed in such drag-and-drop-actions.

The good news is that the solution proposed in the comment above can be applied succesfully each time this bug strikes again.

**Comment by RealRaven2000** [comment]
> Thanks for the quick and efficient support
> 
> While the solution proposed in the comment above perfectly works out, I noticed that the bug (i.e. getting a recent folder list that is different from the latest one) reappeared as soon as I moved a mail to a folder via the QuickMove function. Since I used QuickMove, the recent folder list I get when trying to drag-and-drop an e-mail to the recent folder list of the current folder tab is frozen, i.e. it is the last one (that was correct) before I did the QuickMove action. Moving any e-mail to any folder, e.g. over tabs, updates the recent folder list correctly, but not any more the one proposed in such drag-and-drop-actions.
> 

Thanks  for the additional information - I will look into this further. There shouldn't be a "stale" / "old" recent folders list anywhere, even though jumping to folders with quickMove will definitely move folders to the "top" of the list. It also has its own special recent list (which only contains folders that where successfully navigated to used for moving mails through the quickMove /. quickJump feature) which can be access by typing the key `=` in the search field. quickMove / quickJump is a very quick way of navigating all folders without having to bookmark too much in the QuickFolders toolbar. I would be grateful if you could test further prereleases to address this additional issue.

**Comment by RealRaven2000** [comment]
Fixed in 5.10 - Published 13/06/2022
