### ISSUE TITLE
Reading list: Cannot find the mail, it might have been moved elsewhere in the meantime.

### ISSUE THREAD

**Issue by stratosjl** [RealRaven2000/QuickFolders#265]
The reading list does not seem to be working. It produces the message in the subject. Then, when choosing to search for the message, nothing happens. 

JS log:

Uncaught TypeError: folder is null
    findBookmark chrome://quickfolders/content/quickfolders-bookmarks.js:61
    onClickBookmark chrome://quickfolders/content/quickfolders-bookmarks.js:175
    addMenuItem chrome://quickfolders/content/quickfolders-bookmarks.js:226
quickfolders-bookmarks.js:61:25

**Comment by RealRaven2000** [comment]
A couple things - when you bookmark a fresh item, the URL of the message is saved. If you move the message afterwards, expected behavior is for QuickFolders to update the path to it, this already seems broken in Thunderbird 91. If an item cannot be found the icon changes accordingly:

![image](https://user-images.githubusercontent.com/6314674/169829194-714770ac-1318-4a66-ab7e-06e1eea149a8.png)

When you click on a missing item, QuickFolders should open the advanced search dialog of Thunderbird:
![image](https://user-images.githubusercontent.com/6314674/169830082-539143e0-c40d-4296-8a59-09454928661e.png)

For this is also opens the folder that the message was last stored in - I think in your case that folder was deleted or moved elsewhere. This should normally not be a problem if QF "tracked" the message while moving to a different folder, but obviously we cannot assume this here. So I need to program a fallback folder or deal with the fact there is none first.

**Comment by RealRaven2000** [comment]
Here is a test version that deals with the folder missing or being incorrect. This doesn't fix the underlying problem of the reading list not properly updating anymore. But it should help you track down the missing email:

[QuickFolders-mx-5.10pre10.zip](https://github.com/RealRaven2000/QuickFolders/files/8755028/QuickFolders-mx-5.10pre10.zip)

To install, download the zip file and drag into Thunderbird Add-ons Manager (don't unpack)

**Comment by RealRaven2000** [comment]
I worked on this some more, trying to make the entry correct itself (at least if you use any QuickFolders methods to move the mail, it tries to detect this automatically and correct the URI of the message).

[Uploading QuickFolders-mx-5.10pre14.zip…]()

To install, download the zip file and drag into Thunderbird Add-ons Manager (don't unpack)

**Comment by stratosjl** [comment]
> I worked on this some more, trying to make the entry correct itself (at least if you use any QuickFolders methods to move the mail, it tries to detect this automatically and correct the URI of the message).
> 
> Uploading QuickFolders-mx-5.10pre14.zip…
> 
> To install, download the zip file and drag into Thunderbird Add-ons Manager (don't unpack)

Thank for looking into this! The link to 5.10pre14 does not work, though.

**Comment by RealRaven2000** [comment]
Sorry about that - try this one please:

[QuickFolders-mx-5.10pre27.zip](https://github.com/RealRaven2000/QuickFolders/files/8799600/QuickFolders-mx-5.10pre27.zip)

**Comment by stratosjl** [comment]
Thanks, it seems to be working now!

**Comment by RealRaven2000** [comment]
Please leave open until I release - I close the issues myself on release day :)

thanks for getting back to me though!

**Comment by stratosjl** [comment]
Thanks for your hard work and dedication, much appreciated. TB would offer a very poor experience without your addons.

**Comment by RealRaven2000** [comment]
Fixed in 5.10 - Published 13/06/2022
