### ISSUE TITLE
Feature Request: Clear unread status on messages when dragging them to folders

### ISSUE THREAD

**Issue by Ascar699** [RealRaven2000/QuickFolders#306]
Please consider adding an option in settings that will automatically clear message unread status when I drag a message from inbox to a folder on the toolbar.  This will save an extra manipulation to mark a message as read before moving it.

**Comment by RealRaven2000** [comment]
I will consider making a new option (should this also include quickMove operations). May I ask why you do not set the Thunderbird setting to "Automatically mark messages as read" from Thunderbird general settings?

![image](https://user-images.githubusercontent.com/6314674/188650561-8d2a32c5-11a8-4668-8c20-5e0da7fdb6b8.png)

**Comment by Mantukai** [comment]
Because this, to some extent, helps me mimic Outlook behavior where it is possible to set that messages stay unread unless I mark them read manually.  This allows me to keep some messages more visible when they require attention at a later stage.  I know it is possible to star and tag messages in Thunderbird, however and with Inbox0 objective in mind, as long as there are unread messages in the inbox 0-message target is not achieved and it means there is work left to do.

**Comment by RealRaven2000** [comment]
So here is a test version for the feature. I might restrict this to Pro license holders only in the future, no sure yet. The option looks as follows:

![image](https://user-images.githubusercontent.com/6314674/189134346-8041fc05-db5e-442d-a166-19267761800a.png)

To do: translate new strings to the various languages available in QF (21).

[QuickFolders-mx-5.12.2pre18.zip](https://github.com/RealRaven2000/QuickFolders/files/9527181/QuickFolders-mx-5.12.2pre18.zip)

To install this prerelease: download the zip file, then drag it into Thunderbird Add-ons Manager (without unpacking!)

**Comment by Mantukai** [comment]
Testing, will share feedback once done

**Comment by RealRaven2000** [comment]
New version below. This has all the translations (including vi, zh-CN, zh-TW, es, it, ja, pl, pt, de, ru and more) and the restriction to Pro license holders:

[QuickFolders-mx-5.12.2pre23.zip](https://github.com/RealRaven2000/QuickFolders/files/9527830/QuickFolders-mx-5.12.2pre23.zip)

![image](https://user-images.githubusercontent.com/6314674/189152571-fbd08289-4f3c-4679-83cf-8f000ec59f9a.png)

oops. looks like I missed the last one!

To install this prerelease: download the zip file, then drag it into Thunderbird Add-ons Manager (without unpacking!)

**Comment by RealRaven2000** [comment]
translated the quickMove sentence too:

[QuickFolders-mx-5.12.2pre25.zip](https://github.com/RealRaven2000/QuickFolders/files/9527936/QuickFolders-mx-5.12.2pre25.zip)

![image](https://user-images.githubusercontent.com/6314674/189154573-40df656c-d3be-427b-95ec-aeb043e20fbf.png)

**Comment by RealRaven2000** [comment]
@Mantukai tested the version and made a video which he sent off list.

I watched the video (where you set the status to "Mark mail as read") and it looks like it doesn't clear the "unread" flag for you - what kind of mail account is it? 
I had tested my versions on IMAP and POP3, but I may went across account boundaries (from one account to another, or from IMAP to Local Folders. POP3 seems to work because everything is happening offline anyway) 

I think there is some synchronization issue happening on an IMAP server that undoes the unread / read status after I have set it (or simply forgets to send the status change to the server). Here are the steps:

After the user drops emails to the tab, QuickFolders loops through all messages that are moved, retrieving the database `MsgHdr`:

`Message = messenger.messageServiceFromURI(messageUri).messageURIToMsgHdr(messageUri)`

then (in case of "mark mail as read" is selected)  use the command:

`Message.markRead(true);`

afterwards I prepare the move with some other functions and select the targetFolder, finally adding the message Id to an Array.

This is then passed on to the copyservice (after the complete list has been gone through and the unread / read status has been set) and only then is the copyMessages service called.

`cs.copyMessages(sourceFolder, messageList, targetFolder, isMove, QuickFolders.CopyListener, mw, true);`

I believe everything goes according to plan, however the changed unread / read status is not communicated to the IMAP server in time. Instead the "Move message" command is sent to the server before the "read status" flag has been updated there. This is difficult to debug as setting a breakpoint after `markRead(true)` will most likely give Tb time to update the server and mess with the timing. 

I am hoping that there must be a way to enforce server synchronisation of the source folder in Imap operations, will ask at the TB add-on developers matric chat to see if a Tb employee can help.

**Comment by RealRaven2000** [comment]
I tested setting the unread flag after copyMessages (using MessageId) in the target IMAP folder manually, but the result is the same: the email becomes unread when it is downloaded / synchronized from the server:

targetFolder.msgDatabase.getMsgHdrForMessageID(messageIdList[0]).markRead(true)
targetFolder.msgDatabase.getMsgHdrForMessageID(messageIdList[0]).isRead
   true

Here I show that the message (in the local database) is _indeed_ set as read. But then IMAP begs to differ and sets the mail to unread again. No idea what to do in this case... I do not know whether there is a "message is synchronized" event that I could use to detect the synchronisation finishing and then overwriting the read flag... Obviously this behavior would be even harder to implement using API methods, but I can ask John on Monday anyway whether he could whip up some API code that can do this sort of thing...

**Comment by RealRaven2000** [comment]
Latest comment from @jobisoft 



> I had similar issues when impl. https://phabricator.services.mozilla.com/D155155 and why I split off the IMAP part into https://bugzilla.mozilla.org/show_bug.cgi?id=1787104. **_We first have to wait until the imap online/offline issues are fixed, before the import API can be finished here._**

> ⚙ [D155155 Bug 1646473](https://phabricator.services.mozilla.com/D155155) - Add messages.import(). r=mkmelin
Page Menu Home Phabricator Search Configure Global Search Log In Paths Table of Contents t Hide Panel f Keyboard Reference ? Differential D155155 Bug 1646473 - Add messages.import(). r=mkmelin

> [1787104 - Allow messages.import() to directly import into IMAP folders](https://bugzilla.mozilla.org/show_bug.cgi?id=1787104)
NEW (nobody) in Thunderbird - Add-Ons: Extensions API. Last updated 2022-08-25.

**Comment by RealRaven2000** [comment]
Added some experimental code from [MarkSelectedMessagesRead](https://searchfox.org/comm-esr102/source/mail/base/content/mailCommands.js#568)

[QuickFolders-mx-5.12.2pre33.zip](https://github.com/RealRaven2000/QuickFolders/files/9540166/QuickFolders-mx-5.12.2pre33.zip)

**Comment by RealRaven2000** [comment]
Notes: with the above new version, (prerelease 33) only moved messages from the _first_ source folder will be successfully read-status modified. So it will generate unexpected results if you use quickMove to gather mails from various folders and move them to an IMAP folder later.
The particular line:
`          sourceFolder.markMessagesRead(messageList, isRead);`

Must be run on each source folder (before the messages are moved). I need to look into whether breaking up the command into multiple ones can be done efficiently (the correct way would be to break up the messageList accordingly have calls grouped based on source folder, which is more complicated). Gathering mails across multiple folders during quickMove is an edge case though that most users aren't even aware of. 

Also we still have an issue of supporting *copying* mails: ideally the feature should only affect unread status of the copy and not also the orginating Email to make it more useful. This may require an entirely different strategy as it would need to handle the copied emails on arrival, and not the originating emails before using the `copy` service

**Comment by Mantukai** [comment]
Tested and I can say that we have the desired functionality.  Where we have most unread messages is Inbox from where they have to be moved and this is when clearing the unread flag automatically will save a lot of manipulation - mouse clicking and key presses.

**Comment by RealRaven2000** [comment]
Implemented in 5.13 published today
