### ISSUE TITLE
Remove the term of 'Orphaned Tabs' in all User Interface texts

### ISSUE THREAD

**Issue by tmetro** [RealRaven2000/QuickFolders#315]
Background: I recently upgraded from TB 78 to 102 and discovered the unprofessional way the TB developers removed the movemail account type without either advance depreciation warning or even notice upon first load of 102. 

This is obviously not QuickFolders fault, but after figuring out why one of my accounts had disappeared and finding the Bugzilla ticket explaining the movemail fiasco, I discovered that several of my QuickFolders tabs were broken.

Bug: If I hover the mouse over a broken tab I see:
_No Folder for [Local] - try the 'Find Orphaned Tabs' command._

But I can't find a command resembling that anywhere. Logically I would expect to find that on the tab's context menu, or be able to go into the **Tab-specific properties...** dialog and find a button. But nothing relevant in either place.

I did find a **Remove invalid tabs** option on the main settings menu, but I don't want to remove these tabs.

If **Find Orphaned Tabs** exists somewhere, and does what the name suggests, it also sounds like it wouldn't be the answer. I can already see what tabs are invalid or "orphaned". What I want is an option to **fix** an orphaned tab. If that could be done magically when invoked, then great. Otherwise I'd expect a dialog that lets me select a new target folder from the folder tree for that tab.

I see issue #281 addresses how to fix up the tabs, so this ticket is more about the help text than the how-to.

**Comment by tmetro** [comment]
A [comment](https://github.com/RealRaven2000/QuickFolders/issues/281#issuecomment-1186463562) on issue #281 says:
>deleting all invalid tabs (using QuickFolders tools / find orphaned tabs)

and it shows **find orphaned tabs** in the same spot where I see Remove invalid tabs, so apparently this was renamed, and the mouse-over help text wasn't updated to match.

It looks like I have QuickFolders 5.13.1 installed.

**Comment by RealRaven2000** [comment]
Ok I did a bit of googling and reading up this morning as this was the first time I encountered the "movemail" account type - apparently it is deprecated since Thunderbird 91. In the [bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1625741) there is a lot of discussion, unfortunately nobody stepped up to break out the functionality into an Add-on (which really is an ideal use case for this).

So the main problem here is that there is no way to access the folders directly from Thunderbird 91, because there is no URI schema that supports accessing the existing tabs, at least that's what I would believe. If you wanted to access the old messages you would need to move them into a local folder or POP account, which will then still require QuickFolders to find them again.

The command "Remove invalid Tabs" was indeed called "find orphaned tabs" at one stage, but it was never intended to repair tabs for folders that were move / removed. However there is some code now that repairs the fallout from losing realHostname / realUsername when migrating to 102. This usually runs automatically on startup and tries to find the old folders based on account key (a number).

Making a new function that is able to "reconnect" to a lost or moved folder would make sense (and it could use my quickMove search algorithms to partially match the path), but I am not sure if will help in your particular case - the way I see it the old folders from the "mailmove" account would simply be inaccessible to Thunderbird, without relocating them. However there may be one Add-on able to link to the old account:

https://addons.thunderbird.net/thunderbird/addon/localfolder/

This basically creates a local folder based on any hard drive location, so if you could point it to the root oif the old mailmove account you should be able to access the old messages (?) . If you can export your folder string so we see the original URIs it would be relatively trivial to repair the tabs to point to the new structure.

In QF Settings click on the licenses tab and save configuration:

![image](https://user-images.githubusercontent.com/6314674/193559360-8519570a-669a-4f9b-8f24-5c18302f528e.png)

You can send me the file off list if you like, using the Support tab, bottom link "Contact me"...

**Comment by tmetro** [comment]
> Ok I did a bit of googling and reading up this morning as this was the first time I encountered the "movemail" account type...

I didn't mean to take up your time on the movemail issue, as it is only incidentally related. Sorry. I only mentioned it to establish what led me to have invalid QuickFolder tabs.

> If you wanted to access the old messages you would need to move them into a local folder...

Correct. Which I had already done. (This is actually quite simple as movemail is just Local Folders + a bit of extra code to move messages from /var/spool to your inbox. I just modified the storage path for the stock Local Folders to point to the directory where I had the movemail mail files.)

> ...which will then still require QuickFolders to find them again.

Correct. The account has changed - in my case from server14 to server2 (or correspondingly whatever accounts where affiliated with those server entries).

Thus it is perfectly understandable why this broke QuickFolders and that to fix it the tabs need to get their URI updated to point to the other account. As noted you have addressed how this can be done currently in issue #281.

What I'm trying to do with this bug report is just focus on the error in the help text, so things are easier for the next person to encounter a detached tab, regardless of the cause of the breakage.

And secondarily, suggest some enhancements for fixing a detached tab from the GUI.

**Comment by RealRaven2000** [comment]
I just added new text + translations for the result message after deleting invalid tabs, this will all land in the next version.

**Comment by RealRaven2000** [comment]
Implemented in 5.15.1 - Published 22/Dec/2022
