### ISSUE TITLE
Some O365 quickfolders buttons became orphans (Invalid tabs)

### ISSUE THREAD

**Issue by ardent42c** [RealRaven2000/QuickFolders#321]
Not sure if it's an Thunderbird problem or a QuickFolder problem, but when Thunderbird upgraded to 102.4.1 and in the same time quickfolder was updated, links for many folders became orphans. 
The common thing is, I believe, is that they are all subfolders under one common folder, which has spaces in it's name. 
Something like:  Companies and Person/Local/Fleets , etc.
Had do remove them all and add them again.
BTW, saw that there should be find orphans somewhere, but could not find it (gave up after a while and added everything manually).

**Comment by RealRaven2000** [comment]
This is actually a duplicate of #281 - caused by changes in Thunderbird 102 which [throws away server / username aliases](https://bugzilla.mozilla.org/show_bug.cgi?id=1573690) and uses the actual server / user, which can trash folder URIs for any Add-on (and also built in filters) that store "absolute" folder URIs. It's easy to repair in bulk by using the backup / restore functions on the license tab and doing a little editing.

I attempted to explain it here:
https://github.com/RealRaven2000/QuickFolders/issues/281#issuecomment-1186463562

but it is much easier done than explained, you could have sent me the export and I could have repaired it for you - which can be much faster if you have 30+ tabs than manually recreating them.

**Comment by ardent42c** [comment]
Was <10 tabs, so it was faster for me to just add them back. 
I doubt that most users would find the comment above and prefer to actually do the manual editing. 
Unless an automated solution can be found, I guess this will remain an annoyance for some users. 
Thanks for the response.

**Comment by RealRaven2000** [comment]
> Was <10 tabs, so it was faster for me to just add them back. I doubt that most users would find the comment above and prefer to actually do the manual editing. Unless an automated solution can be found, I guess this will remain an annoyance for some users. 

yes, I revisited the mention of the word "orphan" in my code and it's mainly in the error console, so I started renaming it to point to the "Remove Invalid Tabs" method. I also found that this method will report unified folder tabs (such as "all Sent") as invalid if the "unified folders" view was never active in the current session, so I am working on a fix for that one as well.

**Comment by RealRaven2000** [comment]
> yes, I revisited the mention of the word "orphan" in my code and it's mainly in the error console, so I started renaming it to point to the "Remove Invalid Tabs" method. I also found that this method will report unified folder tabs (such as "all Sent") as invalid if the "unified folders" view was never active in the current session, so I am working on a fix for that one as well.

Added #322 to fix the above
