### ISSUE TITLE
Bling My Tabs: flat style - the default look is . . black on grey!

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [RealRaven2000/QuickFolders#325]
I believe that (on all systems or at least all Windows systems) the following is the default colouration for a 'flat' tab.

![image](https://user-images.githubusercontent.com/47056543/203298976-8fda1c40-b64a-42c4-bd07-e809803aa4b8.png)

That text is too hard to read,  at least when the icon is fairly small. What is needful is lightening the text, i.e. foreground, colour. Black on gray is a poor idea!

QuickFolders 5.14.
Windows 10 Pro - 21H2 (2009: 19044)
Thunderbird 102.5

**Comment by RealRaven2000** [comment]
> That text is too hard to read, at least when the icon is fairly small. What is needful is lightening the text, i.e. foreground, colour. Black on gray is a poor idea!
> 
> QuickFolders 5.14. Windows 10 Pro - 21H2 (2009: 19044) Thunderbird 102.5

it's not even an idea - the problem is that it used a (probably windows specific) system CSS color which may not be well supported by dark mode. once you change the value it will be stored as ordinary 6 digit hex value, such as #FF3456. Setting a default value that works both in light and dark mode is probably not possible at the moment unless I would store multiple values for each foreground / background color.

As you probably know, you can easily change the default text color by using the color picker besides "Uncolored Tabs" on the "bling" page of QuickFolders settings:

![image](https://user-images.githubusercontent.com/6314674/203306848-0e02f155-112b-4c10-ba16-c38512ccc1dc.png)

The coloring system in QF is highly complex already I don't think I am going to add more complexity to guess system colors and automatically compensate for it.

**Comment by LinuxOnTheDesktop** [comment]
Right. Somehow I managed to overlook the following options (perhaps the relevant part of the window had opened off-screen):

![image](https://user-images.githubusercontent.com/47056543/203309862-c6158ee3-00df-4b2f-a5ce-e651615e6218.png)

**Comment by RealRaven2000** [comment]
All colors being "white" points to some bug - either your previous / default settings were overwritten or it is happening while you open the settings dialog. Can you chgeck for errors in error console when you open QF settings?

**Comment by RealRaven2000** [comment]
PS: if you use "Night Vision" for the 4 states (uncolored / active / hovered / drag over), can you select a palette entry for each preview by clicking it?

![image](https://user-images.githubusercontent.com/6314674/203352662-26aedef9-63e1-48dd-8616-ab655edd3c1f.png)

**Comment by LinuxOnTheDesktop** [comment]
Seemingly not. Upon clicking any of the relevant four icons, I see, in each case, exactly this:

![image](https://user-images.githubusercontent.com/47056543/203388462-48779153-9e94-418c-915e-41e435edc792.png)

even though I do have set up (and do actually see, in use), a special colour for, e.g., the currently selected tab.

**Comment by RealRaven2000** [comment]
So that looks like something is completely overwriting the CSS rules maybe with some silly rule that ends in `!important`. What theme are you using and what other Add-ons that might be involved in "skinning" the UI?

**Comment by LinuxOnTheDesktop** [comment]
Aha! Please see [here](https://github.com/RealRaven2000/QuickFolders/issues/326#issuecomment-1324092742).
