### ISSUE TITLE
"Update" downgrades QuickFolder?

### ISSUE THREAD

**Issue by PotatoCarl** [RealRaven2000/QuickFolders#390]
Hi
I am confused. I am sure that a) I installed your pre-version to thunderbird, b) I believe that I have received an update to 6.2.
Now I am back to 6.1.1.
What happens here?

**Comment by RealRaven2000** [comment]
> Hi I am confused. I am sure that a) I installed your pre-version to thunderbird, b) I believe that I have received an update to 6.2. Now I am back to 6.1.1. What happens here?

which pre-version did you install? 6.1.1 is the current version on ATN but it should only overwrite 6.1pre and 6.1.1pre versions.
quickFilters is at 6.2.

**Comment by PotatoCarl** [comment]
sorry, this is my confusion. It is late and I am tired.
I could not sort with quick move into a folder and the filter dialog was not popping up (was working yesterday). After I installed the 6.1.2pre31 ist worked again.
It seems to be a problem with quickfilter, not quickfolder that the filter dialog is not popping up when moving via the quickmove (SHIFT-M I believe)?

**Comment by PotatoCarl** [comment]
After automatic update to 6.1.2 of quickfilter it still works. I don't understand what happens here.

**Comment by RealRaven2000** [comment]
> After automatic update to 6.1.2 of quickfilter it still works. I don't understand what happens here.

[quickFilters 6.2](https://github.com/RealRaven2000/quickFilters/releases/tag/6.2) has a recent bug fix that may apply here. It's dependent on message size, so that's why I only caught it so late.

See [issue 206](https://github.com/RealRaven2000/quickFilters/issues/206) over there, this could be related. Basically it was unable to extract headers (and may have lead to the assistant not showing up in some cases (??)) because it only streamed the first 16kBytes of the message and then exited completely instead of just ending the message read.
