### ISSUE TITLE
Keyboard collision with quick filter toolbar

### ISSUE THREAD

**Issue by Clstei** [RealRaven2000/QuickFolders#392]
There is a collision with QuickFolders and the [Thunderbird quick filter toolbar](https://support.mozilla.org/en-US/kb/quick-filter-toolbar)

I used to have have "M" as magic key for quickMove and "J" for quickJump (premium features); without shift key. But suddenly I cannot use the letters M or J in scope of the Thunderbird quick filter toolbar (the one you open with CTRL-SHIF-K). I can type all other letters in the filter input slot but not M or J. When I pressing M or J nothing happens. Seems that QuickFolders is "stealing" my input.

With disabled QuickFolders plugin the quick filter works well. 

Seems the global search (CTRL-K) is not affected.

This is a regression with new Thunderbird 115.1.1 "Supernova", previously it worked fine.

I am running QuickFolders 6.1.1 (Pro License) with latest Thunderbird 115.1.1 on Windows 10.

**Comment by RealRaven2000** [comment]
Thanks for reporting! We had this problem before in older versions of Thunderbird (there is a global key listener that implements these shortcuts, and it checks the target container (e.g. whether it is one of the search boxes). I bet the type of textbox has changed during the HTML rewrite. Shouldn't be hard to fix,  hopefully. I will see tomorrow.

**Comment by RealRaven2000** [comment]
So, it looks like, while rewriting the 3pane window as HTML5, they name spaced `search-textbox` to now  be  a `xul:search-textbox`. Bit of a gotcha, but easily fixable.

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/5f5e4c1b-f46a-4433-9606-901891a9f3d4)

That's why the shortcut keys are triggered. So far I excluded only `textarea` `textbox` `input` `html:input` `search-textbox` and `findbar`. I also checked the global search box, and that also has a new tag `global-searchbar` and so triggers the bug too. The in-page search (CTRL+F) is not triggered as it uses one of the other tags.

In case you find any additional input elements that are affected, to debug key listener problems we can also enable debug mode and (via right-click) the switch

`extensions.quickfolders.debug.events = true`

this will dump key activity and reaction to the error console.

Here is a test version with quick fix:

[QuickFolders-mx-6.1.2pre16.zip](https://github.com/RealRaven2000/QuickFolders/files/12377937/QuickFolders-mx-6.1.2pre16.zip)

----

To test the version above, download the zip file, drag into Thunderbird Add-ons Manager, do not extract contents or if won't install.

**Comment by Clstei** [comment]
I tested the fix "6.1.2-pre16". Problem is solved!

Shall I close the issue or will you close it?

**Comment by RealRaven2000** [comment]
I will close it, when I release the new version on ATN. Thanks for helping!

**Comment by RealRaven2000** [comment]
Fixed in 6.2 - Published 30/08/2023
