### ISSUE TITLE
Customized icon

### ISSUE THREAD

**Issue by MarcoAtRome** [RealRaven2000/QuickFolders#418]
Under TB supernova is not more possible to have automised icon on the left panel. In the attached file. the icon is a red ball that is present in the tab and in the right panel, but not in the left panel (where is the directory tree...)
![Screenshot 2023-10-22 alle 16 44 16](https://github.com/RealRaven2000/QuickFolders/assets/148703900/dc489c1c-230e-4708-bbc3-c8c62c859efa)
This is a tedious downgrading, affecting one of the many relevant features of QF.
It there  a my mistake in somewhere or is it a bug to be fixed?
Thanks a lot
MR

**Comment by RealRaven2000** [comment]
> This is a tedious downgrading, affecting one of the many relevant features of QF.
> It there a my mistake in somewhere or is it a bug to be fixed?

It's not a mistake, you probably don't know that the 3pane window has been completely rewritten. So I had to completely rewrite it, but it's close to ready for release 6.3. 

See issue #399 - this took a little longer to implement because it wasn't the most important feature and really did NOT want to mess up the folder tree.
Try to install [prerelease 65](https://github.com/RealRaven2000/QuickFolders/issues/399#issuecomment-1749801223). Closing this as duplicate here, comments please over there.

**Comment by MarcoAtRome** [comment]
Dear Axel,
Thanks for the pre-release_65. It works (almost...🙂...) fine.
Now the customised icons are visible in the left pane, but I cannot 
create them directly; I can only create the customised icons in the 
bottom right pane, using the QF menu at the top of this pane.

I should be able to reproduce this situation (from issue #399)

but, in my case (MacOs Sonoma 4.1 - TB 115.3.3),  I'm able to obtain 
only this (see the last line of context menu):

Any way, many thanks for your helpful and continuous support!

Marco

**Comment by RealRaven2000** [comment]
> Dear Axel, Thanks for the pre-release_65. It works (almost...🙂...) fine. Now the customised icons are visible in the left pane, but I cannot create them directly; I can only create the customised icons in the bottom right pane, using the QF menu at the top of this pane. I should be able to reproduce this situation (from issue #399) but, in my case (MacOs Sonoma 4.1 - TB 115.3.3),  I'm able to obtain only this (see the last line of context menu): Any way, many thanks for your helpful and continuous support! Marco

I don't think I saw your screenshots, but I did a test with the latest version (prerelease111) and ti doesn't seem to appear the tree straight away. It's better if you answer the issues here on the Github website, because you can paste screenshots here directly using the built in HTML edito. Further feedback on this topic please over at #399 (you comment there once and it will update you automatically on the topic of icons).,

In my test I used the customize icon command from the folder tree (right-click menu):

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/180cd4ee-a27f-4806-a9e8-4041b5a0adb6)

Then I saw the icon did not update on the tree so I used the command _Repair Tree Icons_ on the QuickFolders tools menu (instead of restarting Thunderbird):

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/a4baf2c2-c23a-43ec-b237-bd8f4dc4597d)

Please go to #399 for further feedback on this!! I will post an update there today as soon as it is fully fixed. Only if you comment (or follow the issue) will you be notified. This issue here is closed as duplicate, so it is not ideal if you follow up _here_.

**Comment by MarcoAtRome** [comment]
With the pre-release_65, the customised icons are visible in the left pane, but I cannot create them directly; I can only create the customised icons in the bottom right pane, using the QF menu at the top of this pane.
I should be able to reproduce this situation (from issue #399)

![Screenshot 2023-10-23 alle 10 13 50](https://github.com/RealRaven2000/QuickFolders/assets/148703900/7110a9b5-6ef8-4765-a479-0f1f32fc9d72)

but, in my case (MacOs Sonoma 4.1 - TB 115.3.3),  I'm able to obtain only this (see the last line of context menu in which is not present <customize icon>):

![no context menu copia](https://github.com/RealRaven2000/QuickFolders/assets/148703900/368e886e-7842-45b3-90b1-cccb19317d69)

**Comment by MarcoAtRome** [comment]
The prerelease 116 has solved the issue

**Comment by MarcoAtRome** [comment]
THANKS!

**Comment by RealRaven2000** [comment]
> The prerelease 116 has solved the issue

We’re not quite done, please leave feedback at #399 not here. 

I closed this issue (#418) as duplicate, because i do not want to keep track of and updating multiple issues for the same feature. I am planning to add code that determines whether a customized icon is already applied on the folder; if the folder has no custom icon, i will hide the command “remove icon”.

i will need you to test this when i upload the new version at #399  - but since you only answer here i so don’t know if it will notify you over there, so you are creating extra work for me. If you could, kindly comment once at #399 or leave an emoji so that it notifies you of new versions automatically- this thread here will not do so.

**Comment by RealRaven2000** [comment]
new version at #399 !
