### ISSUE TITLE
TB 115 no command "empty deleted" in unified folder tab

### ISSUE THREAD

**Issue by freewee** [RealRaven2000/QuickFolders#444]
Hi 
I realize that in TB115, POP and IMAP accounts, in my tab "deleted" (from unified folders), in the menu, there is no " folder commands", and "empty trash".
These options are accessible in the folder list! So no way to empty the trash with the tab, is it normal?
I have no problem with TB115 with only POP accounts.
Thank you

**Comment by RealRaven2000** [comment]
Currently I do not support folder commands for unified folders - because technically they aren't folders. I would have to look into whether it is feasible to allow some of these commands on multiple Inbox / Trash / Spam etc. folders, most likely I would have to program this and iterate all displayed mailboxes and then issue a separate command for each Inbox / Trash etc. Considerable amount of work, and potentially a dangerous command - because I don't think you could undo it.

**Comment by freewee** [comment]
Thank you, I understand and I will do with this!
Thank you for your work!
