### ISSUE TITLE
A folder with ALL unread e-mails (only)

### ISSUE THREAD

**Issue by notDavid** [RealRaven2000/QuickFolders#446]
Hi all,

i can't figure out howto create a folder which displays ALL unread e-mails (and nothing else) from all mailboxes in my account (except Trash and Junk.)

Please advise!
Thank you.

**Comment by RealRaven2000** [comment]
If it is for all folders across all accounts, make a search folder using Ctrl+Shift+F


Ok here is a way to do it for all your _Inboxes_ first of all - this was how I understood the question originally.

1 - enable unified folders
![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/b3c13cbc-6d1c-4ef3-b624-c28c280fffba)

2- right-click the Unified Inbox and select Properties
![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/fce19990-094e-4264-94f1-00162f7f5b46)

3 - Edit properties by adding "Status isn't Read", and click Update
![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/462ded27-103b-4c30-a1c3-c2fedc0aa2fb)

4 - drag the Inbox from Unified folders into the QuickFolders toolbar
![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/28c14a01-1ff8-4297-ba36-eea0bfb9dc1c)


----

If you want to include all emails everywhere you need to create a new Search Folder , use the shortcut Ctrl+Shift+F to open the global search:
![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/f623a33c-c3d9-41a9-b43f-8cb74809e854)

Give it a name, a location where the search folder should be stored (in this example I chose Local Folders) and then click on "Choose..."
![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/70dbca98-a605-4cfb-9665-b52e37799dc5)

Select the Accounts and folders you want to search, then click OK:
![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/debe7c74-500d-4ef7-8674-76f52ae78d8c)
![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/39a4f041-833a-486c-ab12-10d94f76c0bf)
Guess you have to select all folders manually in this step, I haven't seen it automatically selecting the subfolders.


Click Create. Then close the original search window and you will see a new virtual folder with a "looking glass" at the corner.

You can now drag the search folder into QuickFolders toolbar. It may also be a good idea to add the columns Location and Account to see where the original email is located:
![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/f1002c10-bddd-4b16-bcf4-658af951acc0)

**Comment by RealRaven2000** [comment]
PS: I haven't tested what happens if you click on "Mark folder as Read" with the second option across many folders, personally I wouldn't use a global search across everything because it is guaranteed to slow down Thunderbird and will always lag behind. Also I don't think it will add any new folders that you add later on, so you will constantly have to manage it whenever you modify your folder structure. However if you just monitor Inboxes it might be helpful.

Even just having the unified inbox you could just use the built in quickfilter bar to switch to unread mails by clicking the filter button instead of modifying the properties of the Unified inbox:

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/4fd71e01-0209-456b-8278-8a17dde5f4ce)

That way you could also monitor threads in threaded view by disabling Unread:

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/c8b92404-ef83-43bd-84dc-456c7b8e204e)

**Comment by notDavid** [comment]
Thank you for your reply / clarifying @RealRaven2000 !
I'll figure out what works best for me based on what you described.

(personally i'd still prefer having a single "smart folder" with ALL unread e-mails...)
