### ISSUE TITLE
feature request : renaming current folder tab with shortcut

### ISSUE THREAD

**Issue by joomlafun** [RealRaven2000/QuickFolders#450]
Hi,

When you are checking messages in a tab, what about having a shortcut to rename this tab?

And once renamed, automatically get the focus back on the messages.

Kind regards,

**Comment by RealRaven2000** [comment]
Not sure how this would be useful (you know you can use the right-click menu to rename a tab, see below) - why would you need a shortcut, do you need to rename tabs that often? Please be aware that access to shortcuts in Thunderbird is extremely limited as it has many built in shortcuts that Add-ons cannot overwrite. I would only grant shortcuts to extremely important functions that are likely to be used many times within a single session (such as quickMove / quickJump / skip unread folder)

![image](https://github.com/RealRaven2000/QuickFolders/assets/6314674/07ead251-dbee-4078-a7cd-a1f12f6bb42d)

**Comment by joomlafun** [comment]
Yes I do rename tabs very often because I use a lot of them as temporary folders.

I might find a solution with TB keys which are shortcuts that I can associate to a javascript command though.
https://github.com/wshanks/tbkeys

Can you tell me in which .js file is the renaming function present please?

**Comment by RealRaven2000** [comment]
> Can you tell me in which .js file is the renaming function present please?

Most likely here:

https://github.com/wshanks/tbkeys/blob/main/addon/implementation.js

this is very low level stuff, not sure if it would be allowed to be uploaded / hosted at addons.thunderbird.net

I saw there is a "light" version, but not sure if it allows removing Thunderbird shortcuts.

https://addons.thunderbird.net/en-US/thunderbird/addon/tbkeys-lite/?src=search

there is an API approved way of adding (permanent) shortcuts out of the few that are free to Add-ons, which could be used to integrate with QuickFOlders, I just think it's not a feature that a large number of my users will benefit from (I have to curate functions like this because the Add-on is already very complex to configure).

**Comment by joomlafun** [comment]
Thanks for the hint even though I spoke about the quickfolder js file which has the renaming function which can be called from tbkeys.

I will do it without the shortcuts, if thunderbird does not provide it in an easy way then I won't spend time on it.
