### ISSUE TITLE
Customize icon shows first icon in ICO file, instead of one with the appropriate size

### ISSUE THREAD

**Issue by goozak** [RealRaven2000/QuickFolders#51]
When using the "Customize Icon..." feature with an .ico file that contains several sizes, the first icon is used, whether or not its size is appropriate.

For example, in the attached file, the icon used is the 64x64 one — showing only the upper-left part in the folder tree.  The 16x16 icon should be used instead.
![BadIcon](https://user-images.githubusercontent.com/454810/87821257-877e8f00-c83d-11ea-9d52-7f2ecf840a55.png)
[ICO.zip](https://github.com/RealRaven2000/QuickFolders/files/4939650/ICO.zip)

**Comment by RealRaven2000** [comment]
this behaviour is by design. please use images with a single picture size preferably 16×16px or only slightly larger. 

There is an Icon archive on the support site - on the premium page
http://quickfolders.org/premium.html

there is a link to:
http://quickfolders.org/downloads/quickFoldersIcons.zip

**Comment by goozak** [comment]
Oh...  Can I ask why?  It seems arbitrary.  Is it a technical limitation?

**Comment by RealRaven2000** [comment]
yes it is technical. we need to inject a CSS rule to "hack" the folder tree in louder to show tks icon.  multi -image pictures are not supported. also Thunderbird 78 may further restrict access to external files by Add-ons. we are currently converting for 78 i have no n idea what functionality may get lost.
