### ISSUE TITLE
quickMove/quickJump only inside the selected account

### ISSUE THREAD

**Issue by flo2k** [RealRaven2000/QuickFolders#57]
Hi, 

I'm having multiple accounts, and I use the quickMove/quickJump very often. I would like to submit a feature request to enable the search for folders only in the selected account, to not accidentally move the mail to a different account.

Is it possible to implement this feature optionally (by enabling a checkbox) for the premium features?

**Comment by RealRaven2000** [comment]
Not possible currently, but you can exclude folders (and their subfolders) from the search with the advanced tab:

Right-click the tab (you need to create a tab to get at these commands, but you can hide the tab later):#

- open _QuickFolders Commands / tab-specific properties_  - this command needs to be added via QF _Advanced_ settings
![image](https://user-images.githubusercontent.com/6314674/93114287-53471380-f6b2-11ea-8bfd-88c1bc207361.png)

- in Advanced Properties check [x] Omit From quickJump / quickMoive
![image](https://user-images.githubusercontent.com/6314674/93113717-74f3cb00-f6b1-11ea-91fb-f595df8abf63.png)

Unfortunately this setting is per folder, you cannot do it to a whole account, that's because QF currently doesn't store any information about the accounts.

**Comment by flo2k** [comment]
Thank you for your reply. The "Omit from quickJump/quickMove" option is not an option for me, because I do have many folders in all accounts and I use quickJump/quickMove for all accounts, which would limit me to only use it for one.

**Comment by flo2k** [comment]
With that issue https://github.com/RealRaven2000/QuickFolders/issues/118, this issue is also solved, because the new option "Only show results from the current mail account" does exactly what I described here.

Thx a lot. If you don't have any questions, we could close this issue, too.

**Comment by RealRaven2000** [comment]
> With that issue #118, this issue is also solved, because the new option "Only show results from the current mail account" does exactly what I described here.
> 
> Thx a lot. If you don't have any questions, we could close this issue, too.

Yes makes sense. not even sure whether I mentioned this one in the version notes!

**Comment by RealRaven2000** [comment]
For the record, I think I never understood the term "selected account". you meant current folder's account (or the current account). LOL
