### ISSUE TITLE
Drag over color + Dropmarkers when reordering Tabs not working

### ISSUE THREAD

**Issue by simhrod** [RealRaven2000/QuickFolders#79]
I can't make this feature work since the update to TB78. I have selected yellow but when I drag a message over a tab the tab color remains unchanged.

**Comment by RealRaven2000** [comment]
> I can't make this feature work since the update to TB78. I have selected yellow but when I drag a message over a tab the tab color remains unchanged.

Yes this is know because Mozilla removed the `-mox-dragover` CSS pseudo selector - there was a hope that it would be adopted as "`:dragover`" in the HTML Standard but adoption wasn't big enough, so they decided to drop it. It needs to be rewritten somehow using JavaScript. The bug also affects the dropmarkers when reordering tabs using the mouse:

![image](https://user-images.githubusercontent.com/6314674/100222221-b1457200-2f11-11eb-9daa-b15953c291a2.png)

Again something that was relatively inexpensive to do with a CSS selector now has to be recoded in JavaScript

**Comment by RealRaven2000** [comment]
I pinned this one to the top - even though difficult to fix it's really essential and should go into the next minor release (5.1)

**Comment by RealRaven2000** [comment]
Alright, here we go - a test version for you:

[QuickFolders-wx-5.1pre24.zip](https://github.com/RealRaven2000/QuickFolders/files/5618319/QuickFolders-wx-5.1pre24.zip)

- I removed the reliance on `:-mod-drag-over` pseudo selector, manually adding a class "`dragover`" instead
- I added a bunch of `ondragleave` event handlers to better handle expired drag status
- when re-ordering, for calculation of whether the button was previous or next I dropped use of the deprecated "`boxObject`" and check the siblings position of the button instead. That should be a lot more reliable anyway as x-screen position isn't reliable when we have multiple rows of tabs

**Comment by RealRaven2000** [comment]
fixed in release 5.1 on 10/Dec/2020
