### ISSUE TITLE
Useless entries in "Recent Folders" list in case of sub folder

### ISSUE THREAD

**Issue by macdeport** [RealRaven2000/QuickFolders#90]
...
**Folder n** ≫ **Folder n+1 (2)**
**Folder n (2)**
...

When **Folder n** is a QF folder, **without unread mail**, and unread (in this case 2) mails in sub **Folder n+1** lead to 2 entries in place of only 1 in "**Recent Folders**" list i.e.

...
**Folder n** ≫ **Folder n+1 (2)**
...

which is strictly sufficient with the very same information, avoiding redundancy for a better visual comfort.

In fact there is an **instability in display** because at present **the same situation leads to a newer display**:

...
**Folder n (▼2)**
...

I prefer the previous display more informing...

**Comment by RealRaven2000** [comment]
Not quite sure what you mean  - can you make a screenshot?

Behavior by design is that it shows unread mails in the main folder and unread mails in all subfolders, as two separate counts. This should work the same in recent folders...

example: If SmartTemplates / Support has 2 unread mails (but SmartTemplates itself none) it is shown like this:
![image](https://user-images.githubusercontent.com/6314674/102828674-30c54480-43dd-11eb-9fb5-32dd680e3e49.png)
The first figure (before the triangle) denotes only mails in the folder itself:
![image](https://user-images.githubusercontent.com/6314674/102828754-6833f100-43dd-11eb-910e-01beace20c6e.png)
in this case SmartTemplates has 1 unread folder and all subfolders have 2 unread mails.

**Comment by RealRaven2000** [comment]
Are you saying that a subfolder receiving new mail will cause the parent to be shown in recent folders list? I doubt this because that would propagate to _all_ parent folders up to the top.

**Comment by RealRaven2000** [comment]
One odd thing I noticed about the more aggressive recent folders list: The parent node for all newsgroups is added. That would definitely be unwanted:

![image](https://user-images.githubusercontent.com/6314674/102829177-720a2400-43de-11eb-8a39-7f750241901e.png)

**Comment by RealRaven2000** [comment]
> and unread (in this case 2) mails in sub **Folder n+1**

Recent folders is not triggered by unread mails in child folders - it strictly looks at which folders you visited last and which folders got new mails (added unread mails) - this sets the timestamp. I think you seeing the parent folder in the recent folder list is actually caused by a real visit (or added number of unread emails in that folder directly). It is not redundant because it isn't just about unread mails, it's just  about being more recent (and going to a folder and looking at mails is relevant to this information).
